README.md

The README had a typo - s/blod/blob. Fixes.

Fix quick-start URL in README

---

README.md

I'm sure GitHub uses HTTP Strict Transport Security, but let's encourage TLS everywhere.

Prefer URLs which use TLS

---

stroom-core-server/src/main/java/stroom/entity/server/CachingEntityManager.java
stroom-core-server/src/main/java/stroom/entity/server/DocumentEntityServiceImpl.java
stroom-core-server/src/main/java/stroom/entity/server/NamedEntityServiceImpl.java
stroom-core-server/src/main/java/stroom/entity/server/util/StroomEntityManager.java
stroom-core-server/src/main/java/stroom/entity/server/util/StroomEntityManagerImpl.java
stroom-core-server/src/main/java/stroom/feed/server/FeedServiceImpl.java
stroom-entity-shared/src/main/java/stroom/entity/shared/ProvidesNamePattern.java
stroom-security-server/src/main/java/stroom/security/server/UserServiceImpl.java
stroom-util/src/test/java/stroom/util/config/TestStroomProperties.java

ensuring that existing entities are detached from hibernate before being copied
Any copies are prepended with 'Copy of' regardless of destination folder, whilst it might be nice to give it the original name if the folder is different...this would require more work, potentially querying the folder table. The copy can be renamed 'back' if required

detaching entities before copy

---

CHANGELOG.md
stroom-core-server/src/main/java/stroom/node/server/DefaultProperties.java
stroom-statistics-server/src/main/java/stroom/statistics/server/common/search/StatStoreSearchTaskHandler.java
stroom-statistics-server/src/main/java/stroom/statistics/server/common/search/StatisticsSearchServiceImpl.java

An item based window does not use a separate thread. The interruption
of the window thread is casuing problems with the result handler
and loss of data.
Addresses #761

gh-761 Change flowable in SSSTH to use an item vs time based window

---

CHANGELOG.md
stroom-app/src/dist/start.sh

This makes is easier to distinguish stroom and proxy instances on a host

Change start script to use absolute paths for jar, config and logs

---

stroom-app/src/test/java/stroom/kafka/impl/TestKafkaConfigSerialiser.java
stroom-core-shared/src/main/java/stroom/kafka/shared/KafkaConfigDoc.java

Stops people from trying to deserialise objects of any type.

Change kafka config serialisation to use JsonTypeInfo.Id.NAME

---

CHANGELOG.md
stroom-app/src/main/resources/ui/css/webkit-scrollbar.css

Scrollbars now have a white background unless used in a readonly text
area
Fixes #1494

#1494 Scrollbars now have a white background

---

CHANGELOG.md
stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/Event.java
stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/ExtractionTaskProducer.java
stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/StreamEventMap.java
stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/StreamMapCreator.java

Added capacity restriction to the stream event map used in search result
extraction. The previous version was causing out of memory exceptions.

#1882 Add capacity restriction to the stream event map

---

CHANGELOG.md
build.gradle
stroom-core-server/src/test/java/stroom/proxy/repo/TestStroomZipRepository.java
stroom-search/stroom-search-extraction/src/main/java/stroom/search/resultsender/ResultSenderImpl.java
stroom-search/stroom-search-solr/src/main/java/stroom/search/solr/search/SolrSearchFactory.java

Issues relating to Solr index search were identified in the 6.1 branch. This PR aims to bring Solr index searching in the 6.1 branch to a functional state.
Cherry-picks fixes relating to the following issues, which to date have only been released in the v7-beta branch:
- Fixes #1793 : Fixed Solr search query creation.
- Fixes #1791 : Fixed Solr connection test response.
Also resolves the following new issue:
- Fixes #2009 : Fixed Solr searches not returning results after the first search completes.
Additionally, a minor fix was made to a unit test in `TestStroomZipRepository`, which was not succeeding on machines using non-UTC time.

Fix solr search issues

---

CHANGELOG.md
build.gradle
stroom-core-client/src/main/resources/stroom/search/elastic/client/view/ElasticIndexSettingsViewImpl.ui.xml
stroom-core-shared/src/main/java/stroom/search/elastic/shared/ElasticIndexFieldType.java
stroom-core-shared/src/test/java/TestElasticIndexFieldType.java
stroom-pipeline/src/test/java/stroom/pipeline/destination/TestRollingFileDestination.java
stroom-search/stroom-search-elastic/build.gradle
stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/ElasticIndexServiceImpl.java
stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/indexing/ElasticIndexingFilter.java
stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/ElasticSearchTaskHandler.java
stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/SearchExpressionQueryBuilder.java

This PR enables users to:
1. Use Elasticsearch index templates or data streams, whereby an index is created automatically based on a matching template. Previously the index had to exist within the cluster, else Stroom would throw an error.
2. Specify an index name pattern, or list of indices, in an `Elasticsearch Index` entity. Effectively, this enables a Stroom search to target multiple Elasticsearch indices at once.
Closes #2256 and #2257.

Elasticsearch index patterns

---

CHANGELOG.md
stroom-core-client-widget/src/main/java/stroom/widget/popup/client/view/AbstractPopupPanel.java
stroom-core-client-widget/src/main/java/stroom/widget/popup/client/view/Dialog.java
stroom-core-client-widget/src/main/java/stroom/widget/popup/client/view/PopupSupportImpl.java
stroom-core-client-widget/src/main/java/stroom/widget/popup/client/view/ResizableDialog.java
stroom-core-client-widget/src/main/java/stroom/widget/popup/client/view/SimplePopup.java

Allow the user to dismiss a dialog using the keyboard:
- `Escape`: Hides the dialog, equivalent to pressing the `Cancel` button.
- `Ctrl+Enter`: Hides the dialog, returning a `true` result to the handler. Equivalent to pressing the `OK` button.

Close dialogs on Escape/Enter keypress

---

CHANGELOG.md
stroom-app/prod.yml.jinja2

Addresses gchq/stroom-resources#104

gchq/stroom-resources#104 Expose `stroom.ui.helpUrl` in the config.yml

---

CHANGELOG.md
stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobBootstrap.java

Old job node records associated with old jobs are now removed for all
nodes regardless of what node is performing the job bootstrap activity.

#2354 Old job node records are now removed

---

stroom-core-shared/src/main/java/stroom/index/shared/IndexDoc.java

During the migration to REST API services, the properties of `IndexDoc` were changed to type `Integer`. However the member accessors were not updated from type `int`.
This caused properties such as `partitionSize` and `shardsPerPartition` to not be serialised to JSON. See #2672.
This PR updates the property accessor data types such that serialisation occurs as expected.

Fix IndexDoc Integer properties not being serialised

---

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml
stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/ConnectionUtil.java
stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticAggregationTransactionHelper.java
stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticsConfig.java
unreleased_changes/20220427_115333_941__2851.md

PR for #2851 - stroom.statistics.impl.sql.ConnectionUtil has a hard coded > 1 sec slow SQL WARN, can this be configurable instead?

---

stroom-pipeline/src/main/java/stroom/pipeline/destination/RollingDestination.java
stroom-util/src/main/java/stroom/util/io/ByteCountOutputStream.java
unreleased_changes/20220726_131211_183__3012.md

When `RollingFileAppender` writes to a destination with compression enabled, `GZIPOutputStream` first writes a GZIP header to the file.
The current implementation of `RollingDestination` checks the number of bytes written and if greater than zero, writes the XML document header. The problem with this approach is that compressed streams always have a size > 0, so the header is written for each and every event.
This PR adds a `isEmpty` property and corresponding accessor to `ByteCountOutputStream` that is simply set to `false` when any write occurs. This ensures the presence of any data can be tracked, regardless of the use of compression.
Therefore, closes #3012.

Track whether a `ByteCountOutputStream` stream is empty

---

stroom-app/src/main/resources/ui/css/components.css
stroom-app/src/main/resources/ui/css/webkit-scrollbar.css
stroom-core-client-widget/src/main/java/stroom/widget/popup/client/presenter/PopupSize.java
stroom-core-client/src/main/java/stroom/config/global/client/presenter/ManageGlobalPropertyEditPresenter.java
unreleased_changes/20221229_132553_068__3141.md

Closes #3141 
Also resolves the `textarea` scrollbar track not having a dark background.

Increase default width of global property editor dialog

---

stroom-core-client/src/main/java/stroom/query/client/ExpressionModel.java
stroom-core-client/src/main/java/stroom/query/client/TermEditor.java
stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/ExpressionTerm.java
stroom-util-shared/src/main/java/stroom/util/shared/StringUtil.java
unreleased_changes/20230113_091421_364__3111.md

This recreates PR #3157 but with 7.0 as the base.
Reverts the change made in #3113 and now just trims whitespace.
Relates to issue #3111

gh-3111 Revert prev change, now just trim term whitespace

---

stroom-app/src/test/java/stroom/importexport/TestImportExportDashboards.java
stroom-app/src/test/java/stroom/importexport/TestImportExportSerializer.java
stroom-app/src/test/java/stroom/importexport/TestImportExportServiceImpl.java
stroom-app/src/test/java/stroom/importexport/TestImportExportServiceImpl3.java
stroom-app/src/test/java/stroom/statistics/impl/hbase/TestStroomStatsStoreImportExportSerializer.java
stroom-app/src/test/java/stroom/statistics/impl/sql/TestStatisticsDataSourceImportExportSerializer.java
stroom-importexport/stroom-importexport-api/src/main/java/stroom/importexport/api/ExportSummary.java
stroom-importexport/stroom-importexport-impl/build.gradle
stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ContentServiceImpl.java
stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ExportConfig.java
stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ExportContentResourceImpl.java
stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ImportExportSerializer.java
stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ImportExportSerializerImpl.java
stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ImportExportService.java
stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ImportExportServiceImpl.java
unreleased_changes/20230117_111631_086__0.md

Add info logging to export all api resource
```
INFO  2023-01-17T11:10:08.992Z dw-98 - GET /api/export/v1/ s.i.i.ContentServiceImpl       Exporting all config to temp file /tmp/stroom/v7/node1a/resources/0StroomConfig.zip 
INFO  2023-01-17T11:10:10.538Z dw-98 - GET /api/export/v1/ s.i.i.ContentServiceImpl       Exported 433 documents (0 failures) using temp file /tmp/stroom/v7/node1a/resources/0StroomConfig.zip, counts by type:
| Type               | Success | Failed |
|--------------------|---------|--------|
| Dashboard          |      51 |      0 |
| Dictionary         |       4 |      0 |
| Feed               |      72 |      0 |
| Index              |       5 |      0 |
| KafkaConfig        |       2 |      0 |
| Pipeline           |      88 |      0 |
| ProcessorFilter    |      51 …
```

Add export all info logging

---

stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/MenuItemCell.java
stroom-core-client-widget/src/main/java/stroom/widget/popup/client/view/SimplePopup.java
stroom-core-client/src/main/java/stroom/importexport/client/presenter/DependenciesPresenter.java

Resolves compile issues with #3217. Due to the use of `ActionMenuPresenter`, which isn't available in the correct module.

Fix DependenciesPresenter GWT compile errors

---

stroom-core-client/src/main/java/stroom/hyperlink/client/HyperlinkEventHandlerImpl.java
stroom-dashboard-gwt/src/main/java/stroom/dashboard/client/gin/DashboardAppModule.java
unreleased_changes/20230712_090135_261__3595.md

PR for #3595 - `data()` links not working from a directly linked dashboard

---

stroom-pipeline/src/main/java/stroom/pipeline/destination/RollingDestination.java
stroom-util/src/main/java/stroom/util/io/ByteCountOutputStream.java
unreleased_changes/20230809_133740_304__3683.md

This issue is caused by `GZIPOutputStream::getBytesWritten()` returning `0` until the stream is flushed.
Since we want to roll the GZIP stream based on the compressed size, we can't rely on the `getCount()` of `ByteCountOutputStream`, which counts the raw (uncompressed) bytes written to the wrapped stream.
The crux of the issue is that [this line](https://github.com/gchq/stroom/compare/master...p-kimberley:gh-3683?expand=1#diff-1a17ddf65e3d509ca79203b9ef72749ddb0dae29662b142652f35d4257b44b16L112) is testing `getCount()` of the stream. All we need to know is whether any data has been written (and if not, to write out the header).
We can accomplish this by using a simple `boolean` flag that tracks whether any data has been written to the stream.

Fix XML header being written multiple times with RolledFileAppender and compression enabled

---

stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/LmdbDataStore.java
stroom-query/stroom-query-language/src/main/java/stroom/query/language/functions/CountGroups.java
stroom-query/stroom-query-language/src/test/java/stroom/query/language/functions/AbstractFunctionTest.java
unreleased_changes/20240117_124536_290__4014.md

PR for #4014 - Search with a `countGroups()` column causes hang

---

stroom-core-client-widget/src/main/java/stroom/widget/util/client/KeyBinding.java
unreleased_changes/20240515_154322_833__4270.md

PR for #4270 - Typing `ct` into a query term value edit box opens a dialog

---

stroom-core-client/src/main/java/stroom/job/client/presenter/JobNodeListPresenter.java
unreleased_changes/20240904_140627_844__4424.md

PR for #4424 - Current Tasks column doesn't line up on Jobs screen

---

stroom-core-client/src/main/java/stroom/node/client/JobNodeListHelper.java
unreleased_changes/20240904_145126_422__4422.md

PR for #4422 - "Edit Schedule" of "Manage Jobs" should not be displayed for Distributed Jobs

---

stroom-app/src/main/java/stroom/app/App.java
stroom-config/stroom-config-app/src/main/java/stroom/config/app/AppConfig.java
stroom-config/stroom-config-app/src/main/java/stroom/config/app/SessionConfig.java
stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml
stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/ConfigProvidersModule.java
stroom-config/stroom-config-global-impl/src/test/java/stroom/config/global/impl/TestConfigMapper.java
stroom-core-shared/src/main/java/stroom/security/shared/SessionListResponse.java
stroom-dropwizard-common/src/main/java/stroom/dropwizard/common/SessionListeners.java
stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityFilter.java
stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SessionListListener.java
stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SessionSecurityModule.java
stroom-util/src/main/java/stroom/util/logging/LambdaLogger.java
stroom-util/src/main/java/stroom/util/servlet/UserAgentSessionUtil.java
unreleased_changes/20250115_150813_268__4693.md

PR for #4693 - sessionList is very slow v7.5 on a cluster

---

stroom-core-shared/src/main/java/stroom/security/shared/User.java
stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/JwtUtil.java
stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/StroomUserIdentityFactory.java
stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserServiceImpl.java
stroom-security/stroom-security-impl/src/test/java/stroom/security/impl/TestStroomUserIdentityFactory.java
stroom-security/stroom-security-impl/src/test/java/stroom/security/impl/TestUserServiceImpl.java
unreleased_changes/20250204_162439_448__4759.md

PR for #4759 - `Updating IDP user info` spam in the logs

---

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml
stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/ProxyOpenIdConfig.java
stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml
stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/ExternalIdpConfigurationProvider.java
stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/StroomOpenIdConfig.java
stroom-security/stroom-security-openid-api/src/main/java/stroom/security/openid/api/AbstractOpenIdConfig.java
unreleased_changes/20250403_094717_358__4837.md

PR for #4837 - OIDC config GET uses httpClient, but token calls use jerseyClient

---

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml
stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/RemoteFeedStatusService.java
stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml
stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/CertificateExtractorImpl.java
stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/GetFeedStatusRequestAdapter.java
stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/ReceiveDataConfig.java
stroom-receive/stroom-receive-common/src/test/java/stroom/receive/common/TestCertificateExtractorImpl.java
stroom-util/src/main/java/stroom/util/cert/CertificateExtractor.java
stroom-util/src/main/java/stroom/util/cert/DNFormat.java
stroom-util/src/test/java/stroom/util/cert/TestCertificateExtractor.java
unreleased_changes/20250715_152934_118__5030.md

PR for #5030 - Support legacy DN format when extracting identity from certificates
