stroom-dashboard-client/src/main/java/stroom/dashboard/client/query/QueryPresenter.java, stroom-dashboard-server/build.gradle, stroom-dashboard-server/src/main/java/stroom/dashboard/server/DownloadQueryActionHandler.java, stroom-dashboard-server/src/main/java/stroom/dashboard/server/JsonUtil.java, stroom-dashboard-server/src/main/java/stroom/dashboard/server/SearchRequestMapper.java, stroom-dashboard-shared/src/main/java/stroom/dashboard/shared/DownloadQueryAction.java
=> gh365 Add download query btn

build.gradle, stroom-app/Dockerfile, stroom-core-server/build.gradle, stroom-integrationtest/src/integrationTest/java/stroom/test/ContentImportService.java, stroom-statistics-server/src/main/java/stroom/statistics/server/stroomstats/internal/StroomStatsInternalStatisticsService.java
Change stroom-stats event generation to use v3 of the stats xml schema and change the core-xml-schemas content pack used in setupSampleData and the docker builds to v1.1
=> Uplift stats schema

build.gradle, stroom-app-gwt/src/main/resources/stroom/app/App.gwt.xml, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/TablePresenter.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/UrlDetector.java, stroom-dashboard-client/src/test/java/stroom/dashboard/client/table/UrlDetectorTest.java
This will detect field values of the following form
[:title](:url)
and display them as clickable links
=> Adding URL Detection and presentation to table view

stroom-core-server/src/main/java/stroom/node/server/StroomPropertyService.java, stroom-core-server/src/main/java/stroom/node/server/StroomPropertyServiceImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/DelegateExtensionFunctionDefinition.java, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/FetchAnnotation.java, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/FetchJson.java, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/GenerateURL.java, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/JsonToXml.java, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/StroomXSLTFunctionLibrary.java
=> Annotation lookup

CHANGELOG.md, stroom-core-server/src/main/java/stroom/io/StreamCloser.java, stroom-index/src/main/java/stroom/index/server/IndexShardWriterImpl.java, stroom-util/src/main/java/stroom/util/concurrent/SimpleExecutor.java, stroom-util/src/main/java/stroom/util/zip/StroomZipFile.java, stroom-util/src/test/java/stroom/util/test/TestState.java
=> gh-484 Remove finalize methods

CHANGELOG.md, stroom-core-server/src/main/java/stroom/streamtask/server/ProxyAggregationExecutor.java, stroom-core-server/src/main/java/stroom/task/server/TaskManagerImpl.java, stroom-integrationtest/src/test/java/stroom/streamtask/server/ProxyAggregationLoader.java, stroom-integrationtest/src/test/java/stroom/streamtask/server/TestProxyAggregationTask.java, stroom-integrationtest/src/test/java/stroom/task/server/TestTaskManagerImpl.java
=> Gh 490 proxy aggregation rejected execution exception

CHANGELOG.md, stroom-core-server/src/main/java/stroom/proxy/repo/StroomZipRepositoryProcessor.java
=> gh-494 Fix issue of proxy aggregation never stopping

CHANGELOG.md, stroom-statistics-server/src/main/java/stroom/statistics/server/common/StatisticEventStoreFactoryImpl.java, stroom-statistics-server/src/main/java/stroom/statistics/server/common/StatisticsDataSourceCacheImpl.java, stroom-statistics-server/src/main/java/stroom/statistics/server/common/search/StatStoreSearchDataSourceProvider.java, stroom-statistics-server/src/main/java/stroom/statistics/server/common/search/StatStoreSearchTaskHandler.java
=> Gh 539 stat search failing after import

CHANGELOG.md, stroom-core-server/src/main/java/stroom/streamstore/server/fs/FileSystemStreamStoreImpl.java
Fixed bug whereby viewing folders that contained zero permitted feeds would return all permitted feeds across system.
=> Gh 573 data tab

CHANGELOG.md, stroom-dashboard-server/src/main/java/stroom/dashboard/server/DownloadQueryActionHandler.java
=> Gh 480 change api json to fetch all

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/FormatDate.java, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/StroomExtensionFunctionCall.java, stroom-pipeline/src/test/java/stroom/pipeline/server/xsltfunctions/TestFormatDate.java
Add junit tests for time zone parsing
Addresses #735
=> gh-735 Change FormatDate to use case insensitive parse

CHANGELOG.md, stroom-statistics-server/src/main/java/stroom/statistics/server/common/search/StatStoreSearchTaskHandler.java, stroom-statistics-server/src/main/java/stroom/statistics/server/common/search/StatisticsSearchServiceImpl.java
=> gh-770 Change sql stats Flowable to use window() and call clear()

CHANGELOG.md, stroom-dashboard/src/main/java/stroom/dashboard/server/download/ExcelTarget.java
=> gh-766 Add protection from null toString() value in ExcelTarget

CHANGELOG.md, stroom-core-server/src/main/resources/stroom/db/migration/mysql/V6_0_0_32__Rename_old_NStatFilter_references.sql
=> gh-798 Add DB mig script to replace NStatFilter type references

CHANGELOG.md, stroom-core-server/src/main/resources/stroom/db/migration/mysql/V6_0_0_33__Rename_old_Stream_Type_references.sql
=> gh-800 Add DB mig script 33 to update Stream Type to streamTypeName

CHANGELOG.md, build.gradle, stroom-dashboard-server/src/main/java/stroom/dashboard/server/SearchBusPollActionHandler.java, stroom-index-server/src/main/java/stroom/index/server/StroomIndexQueryResource.java, stroom-index-server/src/main/java/stroom/search/server/AsyncSearchTaskHandler.java, stroom-index-server/src/main/java/stroom/search/server/ClusterSearchTaskHandler.java
=> Gh 830 api queries timing out

CHANGELOG.md, stroom-app/build.gradle, stroom-app/src/main/java/stroom/startup/App.java, stroom-util/src/main/java/stroom/util/db/DbUtil.java
=> Gh 859 wait for db conn

stroom-explorer-server/src/main/java/stroom/explorer/server/ExplorerServiceImpl.java
Ok turns out it was quite easy to fix
=> recursive delete

stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerTreeModel.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PipelineStructurePresenter.java, stroom-entity-shared/src/main/java/stroom/entity/shared/DocRefUtil.java, stroom-index-server/src/main/java/stroom/search/server/extraction/ExtractionTaskHandler.java
added a doc ref for None selections that can be accessed anywhere, used in search extraction to determine if the configuration is wrong
=> Made a distinct condition for 'None' extraction pipeline with extraction enabled

CHANGELOG.md, stroom-proxy/src/main/java/stroom/proxy/handler/ProxyRequestHandler.java
=> gh-966 Proxy was always reporting zero bytes in the receive log.

CHANGELOG.md, build.gradle, stroom-core-shared/src/main/java/stroom/streamstore/shared/StreamType.java, stroom-integrationtest/src/integrationTest/java/stroom/pipeline/server/task/TranslationTest.java
=> Gh 970 add records stream type

CHANGELOG.md, stroom-app/dev.yml, stroom-app/prod.yml, stroom-security-server/src/main/java/stroom/security/server/DocumentPermissionServiceImpl.java, stroom-security-server/src/main/java/stroom/security/server/UserAppPermissionServiceImpl.java
=> gh-1050 Prevent creation of permission entries if key already exists.

CHANGELOG.md, build.gradle, stroom-app/docker/Dockerfile, stroom-app/proxy-docker/Dockerfile, stroom-core-server/build.gradle, stroom-core-server/src/main/java/stroom/node/server/DefaultProperties.java, stroom-core-server/src/main/java/stroom/node/server/HeapHistogramService.java, stroom-core-server/src/main/java/stroom/node/server/HeapHistogramStatisticsExecutor.java, stroom-core-server/src/test/java/stroom/node/server/TestHeapHistogramStatisticsExecutor.java
=> gh-1084 Change HeapHisto stat to use DiagnosticCommandMBean approach

CHANGELOG.md, stroom-dashboard-server/src/main/java/stroom/dashboard/server/SearchRequestMapper.java
=> gh-1100 Change SearchRequestMapper to not assumed ascending sort

CHANGELOG.md, stroom-app/src/dist/start.sh
=> gh-1130 Change `start.sh` so it works when realpath is not installed.

CHANGELOG.md, buildLocalDocker.sh, stroom-proxy/src/main/java/stroom/proxy/handler/ForwardStreamHandlerFactory.java
=> Change proxy remote url healtch check to accept 406 (feed not defined)

.idea/runConfigurations/Stroom_Proxy__Dropwizard_.xml, CHANGELOG.md, build.gradle, buildDockerImages.sh, stroom-app/build.gradle, stroom-app/docker/Dockerfile, stroom-app/proxy-docker/Dockerfile, stroom-app/proxy-prod.yml, stroom-app/proxy.yml, stroom-app/src/main/java/stroom/startup/App.java, stroom-app/src/main/java/stroom/startup/Config.java, stroom-core-server/src/main/java/stroom/feed/server/FeedStatusResource.java, stroom-core-server/src/main/java/stroom/util/HealthCheckUtils.java, stroom-pipeline/build.gradle, stroom-pipeline/src/main/java/stroom/pipeline/server/xsltfunctions/FetchJson.java, stroom-proxy/build.gradle, stroom-proxy/src/main/java/stroom/proxy/guice/ProxyConfig.java, stroom-proxy/src/main/java/stroom/proxy/guice/ProxyModule.java, stroom-proxy/src/main/java/stroom/proxy/handler/ForwardStreamHandlerFactory.java, stroom-proxy/src/main/java/stroom/proxy/handler/RemoteFeedStatusService.java, stroom-proxy/src/test/java/stroom/proxy/handler/TestProxyHandlerFactory.java, stroom-statistics-server/build.gradle, stroom-statistics-server/src/main/java/stroom/statistics/server/sql/datasource/StatisticsDataSourceMarshaller.java, stroom-statistics-shared/build.gradle, stroom-statistics-shared/src/main/java/stroom/statistics/shared/StatisticsDataSourceData.java, travis.before_script.sh
=> Gh 1140 add feed status healthcheck

CHANGELOG.md, stroom-entity-shared/src/main/java/stroom/entity/shared/EntityIdSet.java, stroom-explorer-server/src/integrationTest/java/stroom/db/migration/mysql/V6_0_0_9__ProcessingFilterIT.java
=> gh-1149 Change the way EntryIdSet is unmarshalled

CHANGELOG.md, stroom-app/src/main/java/stroom/startup/App.java, stroom-core-server/src/main/java/stroom/dictionary/server/DictionaryResource.java, stroom-core-server/src/main/java/stroom/feed/server/FeedStatusResource.java, stroom-proxy/src/main/java/stroom/proxy/security/ProxySecurityFilter.java, stroom-ruleset-server/src/main/java/stroom/ruleset/server/RuleSetResource.java
=> gh-1204 Fix ProxySecFilt to use correct API key on feedStatus requests

CHANGELOG.md, stroom-core-server/src/main/java/stroom/proxy/repo/ProxyRepositoryManager.java, stroom-core-server/src/main/java/stroom/proxy/repo/StroomZipRepository.java, stroom-core-server/src/test/java/stroom/proxy/repo/TestStroomZipRepository.java, stroom-core-server/src/test/resources/logback-test.xml, stroom-proxy/build.gradle, stroom-proxy/src/main/java/stroom/proxy/repo/ProxyRepositoryReader.java, stroom-proxy/src/test/java/stroom/proxy/repo/TestProxyRepositoryReader.java, stroom-proxy/src/test/resources/logback-test.xml
=> Gh 1205 proxy clean deleting repo root

CHANGELOG.md, stroom-app/src/main/java/stroom/startup/App.java, stroom-app/src/main/java/stroom/startup/FilterUtil.java, stroom-core-server/src/main/java/stroom/servlet/CacheControlFilter.java
=> Gh 1293 fix cache control filter

stroom-app/src/main/resources/ui/index.html
Added html compliant tags - minor fix
=> Added html compliant tags - minor fix

stroom-app/src/main/resources/ui/css/editor.css
Fixed missing default font-family - improved browser compatibility
=> Fixed missing default font-family

stroom-app/src/main/resources/ui/css/standard.css
Fixed missing default font-family - improved browser compatibility
=> Fixed missing default font-family - improved browser compatibility

.idea/runConfigurations/Stroom_Proxy__Dropwizard_.xml, CHANGELOG.md, stroom-app/src/main/java/stroom/startup/App.java, stroom-app/src/main/java/stroom/startup/FilterUtil.java, stroom-app/src/main/java/stroom/startup/SpringUtil.java, stroom-security-api/src/main/java/stroom/security/UserTokenUtil.java, stroom-security-server/src/main/java/stroom/security/server/SecurityFilter.java
=> Gh 1295 bypass sec filter

CHANGELOG.md, stroom-core-client/src/main/java/stroom/monitoring/client/presenter/DatabaseTablesMonitoringPresenter.java, stroom-core-shared/src/main/java/stroom/node/shared/DBTableStatus.java, stroom-core-shared/src/main/java/stroom/node/shared/DbStatusResource.java, stroom-core/src/main/java/stroom/core/db/DBTableService.java, stroom-util-shared/src/main/java/stroom/util/shared/CompareUtil.java
=> gh-1394 Fix duplicate tables appearing in Monitoring -> Database Tables

stroom-app/dev.yml, stroom-app/prod.yml, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/AppConfigMonitor.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/ConfigMapper.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/GlobalConfigService.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/validation/CustomConstraintValidatorFactory.java, stroom-docstore/stroom-docstore-impl-db/src/main/java/stroom/docstore/impl/db/DBPersistence.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaServiceConfig.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaValueConfig.java, stroom-statistics/stroom-statistics-impl-hbase/src/main/java/stroom/statistics/impl/hbase/internal/StroomStatsInternalStatisticsService.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/entity/StatisticsDataSourceCacheImpl.java, stroom-util-shared/src/main/java/stroom/util/shared/PropertyPath.java
=> Gh 1441 db prop value ignored

CHANGELOG.md, stroom-core/src/main/java/stroom/core/query/SuggestionsResourceImpl.java, stroom-core/src/test/java/stroom/core/query/TestSuggestionsResourceImpl.java
(cherry picked from commit b74a9b269b6294f3346c5f5001f10c1a8ace69ae)
Addresses #1454
=> gh-1454 Fix NPE in feed name suggestion box

CHANGELOG.md, stroom-core-client/src/main/java/stroom/data/client/presenter/AbstractMetaListPresenter.java
=> Gh 1450 meta filter ignored mk2

stroom-kafka/stroom-kafka-impl/src/main/java/stroom/kafka/pipeline/StandardKafkaProducer.java
Resolve gh-1433 to allow XML payloads.
Limitations: Currently UTF-8 only and  requires well formed XML payloads.
=> gh-1433 XML message generation in StandardKafkaProducer

CHANGELOG.md, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java
=> Resolve gh-1491 Download stream failing

CHANGELOG.md, stroom-core-client/src/main/java/stroom/processor/client/presenter/ProcessorListPresenter.java, stroom-core-shared/src/main/java/stroom/processor/shared/Processor.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterServiceImpl.java
=> Resolve gh-1471 Processor/Filter names not shown

stroom-core/src/test/resources/samples/config/Search/Test_Dashboard_With_Missing_Dictionary.Dashboard.e793783c-f7b1-4fda-9350-a9fd28126908.json
Make the Test Dashboard a bit more typical.
=> Add components to Test Dashboard Missing Dictionary

CHANGELOG.md, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/datasource/DataSourceUrlConfig.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/datasource/SimpleDataSourceProviderRegistry.java
=> gh-1529 Fix error when selecting datasource in new dashboard

CHANGELOG.md, stroom-app/dev.yml, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobBootstrap.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobSystemConfig.java, stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeConfig.java
=> Gh 1545 enable processing

CHANGELOG.md, stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionModule.java, stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionRulesResourceImpl.java, stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionRulesService.java, stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionRulesServiceImpl.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaServiceImpl.java
=> #1546 Fix opening and editing of data retention rules

CHANGELOG.md, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerNode.java, stroom-core/src/main/java/stroom/core/query/SuggestionsServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/NewUIExplorerResource.java, stroom-explorer/stroom-explorer-impl/src/test/resources/logback-test.xml, stroom-util-shared/src/main/java/stroom/util/shared/UniqueIdentity.java, stroom-util/build.gradle, stroom-util/src/main/java/stroom/util/docref/DocRefPredicateFactory.java, stroom-util/src/main/java/stroom/util/string/StringPredicateFactory.java, stroom-util/src/test/java/stroom/util/docref/TestDocRefPredicateFactory.java
=> gh-1611 Add filtering on UUID.

CHANGELOG.md, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsVolumeConfig.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexVolumeGroupServiceImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/selection/VolumeConfig.java
=> Gh 1639 default index vol limit prop

stroom-app/prod.yml
Add environmental variables to allow control of default volume creation
=> Default vol creation env var

CHANGELOG.md, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/RuleSetListPresenter.java, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/RuleSetSettingsPresenter.java
=> Gh 1627 ruleset up down btns

CHANGELOG.md, stroom-statistics/stroom-statistics-impl-sql/src/main/resources/stroom/statistics/impl/sql/db/migration/V07_00_00_001__Schema.sql
Tested with group replication enabled, seems OK now.
=> Fixes #1632 - Allow use of MySQL group replication feature with sql stats

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/writer/HTTPAppender.java
Not a complete solution, but addresses some of the issues raised by #1680
=> Add readTimeout to HTTPAppender

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java
=> Fix GH-1671 hex-to-oct not working

CHANGELOG.md, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionPolicyListPresenter.java, stroom-core-client/src/main/java/stroom/receive/rules/client/view/DataRetentionRuleViewImpl.java
=> gh-1673 Increase retention age spinner max to 9999

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/ParseUri.java
=> gh-1670 Make parse-uri xslt func return null for no port

CHANGELOG.md, stroom-core-shared/src/main/java/stroom/data/shared/StreamTypeNames.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/StreamTypeExtensions.java
=> Fix gh-1695 Records stream types not handled correctly.

stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/StreamMapCreator.java
=> Ensure that searches over deleted streams complete

CHANGELOG.md, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterResourceImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterServiceImpl.java
=> Fix gh-1701 UI crash after selecting pipeline for processing

CHANGELOG.md, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java
=> Fix gh-1664 crash when deleting all streams associated with pipeline

CHANGELOG.md, buildDockerImages.sh, stroom-app/docker/Dockerfile, stroom-app/docker/docker-entrypoint.sh, stroom-app/prod.yml
=> gh-1699 Add a docker managed volume for the ref data store

CHANGELOG.md, stroom-core-client-widget/src/main/java/stroom/widget/dropdowntree/client/view/QuickFilterTooltipUtil.java, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerTreeFilter.java, stroom-core/src/main/java/stroom/core/query/SuggestionsServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/NewUIExplorerResource.java, stroom-util/src/main/java/stroom/util/docref/DocRefPredicateFactory.java, stroom-util/src/main/java/stroom/util/filter/QuickFilterPredicateFactory.java, stroom-util/src/test/java/stroom/util/docref/TestDocRefPredicateFactory.java, stroom-util/src/test/java/stroom/util/filter/TestQuickFilterPredicateFactory.java
=> gh-1694 Fix UUID filtering in quick filters

CHANGELOG.md, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/search/StatisticsSearchServiceImpl.java
=> Gh 1829 sql stats no cols

CHANGELOG.md, stroom-core-shared/src/main/java/stroom/security/shared/DocPermissionResource.java, stroom-core-shared/src/main/java/stroom/security/shared/DocumentPermissions.java, stroom-core-shared/src/main/java/stroom/security/shared/FilterUsersRequest.java, stroom-core-shared/src/main/java/stroom/security/shared/FindUserCriteria.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/AdvancedUserListPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/DocumentPermissionsPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/DocumentPermissionsTabPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/DocumentUserListPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/UserDataProvider.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/UsersAndGroupsTabPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/view/UserListViewImpl.java, stroom-security/stroom-security-identity-db/src/main/java/stroom/security/identity/db/AccountDaoImpl.java, stroom-security/stroom-security-identity-db/src/main/java/stroom/security/identity/db/TokenDaoImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountResource.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/token/TokenResource.java, stroom-security/stroom-security-impl-db/src/main/java/stroom/security/impl/db/UserDaoImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/db/UserDaoImplTest.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocumentPermissionResource.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserDao.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserService.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserServiceImpl.java, stroom-util-shared/src/main/java/stroom/util/shared/filter/FilterFieldDefinition.java
=> gh-1737 gh-1832 Fix quick filters for users/groups

CHANGELOG.md, stroom-annotation/stroom-annotation-impl/src/main/java/stroom/annotation/impl/AnnotationResourceImpl.java, stroom-app/src/main/resources/ui/css/stroom-annotation.css, stroom-core-client/src/main/java/stroom/annotation/client/AnnotationEditPresenter.java, stroom-core-client/src/main/java/stroom/annotation/client/AnnotationEditViewImpl.java, stroom-core-client/src/main/java/stroom/annotation/client/ChooserViewImpl.java, stroom-core-client/src/main/resources/stroom/annotation/client/AnnotationEditViewImpl.ui.xml, stroom-core-shared/src/main/java/stroom/annotation/shared/AnnotationResource.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserServiceImpl.java, stroom-util/src/main/java/stroom/util/filter/FilterFieldMapper.java, stroom-util/src/main/java/stroom/util/filter/FilterFieldMappers.java, stroom-util/src/main/java/stroom/util/filter/QuickFilterPredicateFactory.java
=> gh-1829 Stop Annotations recording changes for empty title/subject

CHANGELOG.md, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/search/SQLTagValueWhereClauseConverter.java
=> gh-1781 Fix SQL stats handling of NOT() with >1 children

CHANGELOG.md, stroom-security/stroom-security-impl-db/src/main/java/stroom/security/impl/db/UserDaoImpl.java
=> gh-1657 Remove INTERNAL_PROCESSING_USER from Users list

CHANGELOG.md, stroom-core-shared/src/main/java/stroom/dashboard/shared/Search.java, stroom-dashboard/stroom-dashboard-impl/build.gradle, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/DashboardResourceImpl.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/datasource/RemoteDataSourceProvider.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/search/StatStoreCriteriaBuilder.java, stroom-statistics/stroom-statistics-impl-sql/src/test/java/stroom/statistics/impl/sql/TestSQLStatisticEventStore2.java
=> Gh 1782 stats npe empty and

CHANGELOG.md, stroom-docstore/stroom-docstore-impl/src/main/java/stroom/docstore/impl/StoreImpl.java, stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ImportExportSerializerImpl.java
=> gh-1809 Fix check for exsting docref, catch PermissionException

CHANGELOG.md, stroom-core-client/src/main/java/stroom/data/client/presenter/DataUploadPresenter.java, stroom-core-client/src/main/java/stroom/dispatch/client/RestFactoryImpl.java, stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionRulesServiceImpl.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/DataVolumeService.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataServiceImpl.java, stroom-docstore/stroom-docstore-impl/src/main/java/stroom/docstore/impl/StoreImpl.java, stroom-dropwizard-common/src/main/java/stroom/dropwizard/common/PermissionExceptionMapper.java
=> Gh 1835 1836 data import perms

CHANGELOG.md, stroom-core-shared/src/main/java/stroom/process/shared/ExpressionUtil.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/main/AbstractComponentPresenter.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/FieldsManager.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/RenameFieldPresenter.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/TablePresenter.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/TableRow.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/cf/ExpressionMatcher.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/cf/RulesPresenter.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/text/TextPresenter.java, stroom-dashboard-shared/src/main/java/stroom/dashboard/shared/IndexConstants.java
=> Gh 1874 stream id col name

CHANGELOG.md, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/AnnotationManager.java, stroom-dashboard-shared/src/main/java/stroom/dashboard/shared/IndexConstants.java
=> Gh 1885 anno btn

CHANGELOG.md, stroom-core-client-widget/build.gradle, stroom-core-client-widget/src/main/java/stroom/widget/customdatebox/client/ClientDateUtil.java, stroom-core-client-widget/src/test/java/stroom/widget/customdatebox/client/TestClientDateUtil.java, stroom-core-client/src/main/java/stroom/query/client/Term.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/TablePresenter.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/cf/ExpressionMatcher.java, stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/cf/RulesPresenter.java, stroom-util-shared/src/main/java/stroom/util/shared/CompareUtil.java
=> gh-1877 Add support for decimals in cond formatting (dates broken)

CHANGELOG.md, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/ExtractionTaskProducer.java, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/StreamMapCreator.java
=> gh-1877 Fix searches hanging generally and when streams deleted

CHANGELOG.md, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-config/stroom-config-common/src/main/java/stroom/config/common/ConnectionPoolConfig.java, stroom-db-util/src/main/java/stroom/db/util/AbstractFlyWayDbModule.java, stroom-security/stroom-security-api/src/main/java/stroom/security/api/ProcessingUserIdentityProvider.java, stroom-security/stroom-security-api/src/main/java/stroom/security/api/UserIdentity.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/ProcessingUserIdentityProviderImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityContextImpl.java, stroom-security/stroom-security-mock/src/main/java/stroom/security/mock/MockProcessingUserIdentityProvider.java
=> gh-1900 Fix inter-node task assignment, change proc user equality tests

CHANGELOG.md, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterImportExportHandlerImpl.java
=> Fix gh-1848 NPE when importing certain processor filters

CHANGELOG.md, stroom-app/dev.yml, stroom-app/prod.yml.jinja2, stroom-app/src/test/java/stroom/test/DatabaseCommonTestControl.java, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsVolumeConfig.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsVolumeService.java, stroom-data/stroom-data-store-util/src/test/java/stroom/data/store/util/TestStreamDumpTool.java, stroom-data/stroom-data-store-util/src/test/java/stroom/data/store/util/TestStreamGrepTool.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexVolumeGroupServiceImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/selection/VolumeConfig.java
=> Gh 1893 change delimited string props

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/writer/XMLWriter.java, stroom-pipeline/src/test/java/stroom/pipeline/xml/converter/json/TestJSONParser.java
=> Gh 1733 support cdata output

CHANGELOG.md, stroom-core-client-widget/src/main/java/stroom/editor/client/view/EditorViewImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceData.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoadTaskHandler.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoaderImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/AbstractLookup.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/BitmapLookup.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/Lookup.java
=> gh-1938 Fix missing ref loading errors/warnings, improve messages

CHANGELOG.md, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataDownloadTaskHandler.java
=> Fix gh-1949 Unable to download streams from multiple feeds

CHANGELOG.md, stroom-core-server/src/main/java/stroom/proxy/repo/StroomStreamProcessor.java, stroom-proxy/src/main/java/stroom/proxy/repo/ProxyForwardingFileSetProcessor.java, stroom-util/src/main/java/stroom/util/net/HostNameUtil.java
=> gh-1954 Change ReceivedPath to try using an env var first

CHANGELOG.md, stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionRulesServiceImpl.java, stroom-docstore/stroom-docstore-impl/src/main/java/stroom/docstore/impl/StoreImpl.java
=> Fix gh-1808 manage policies permission not working

CHANGELOG.md, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataFetcher.java
=> gh-1960 Fix handling of empty streams in data preview

CHANGELOG.md, stroom-job/stroom-job-api/src/main/java/stroom/job/api/ScheduledJob.java
=> gh-1974 Fix job screen only showing one job

CHANGELOG.md, stroom-core-client-widget/src/main/java/stroom/widget/tooltip/client/presenter/TooltipUtil.java, stroom-core-client/src/main/java/stroom/data/client/presenter/MetaInfoPresenter.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/CharReader.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataFetcher.java, stroom-util-shared/src/main/java/stroom/util/shared/DataRange.java
=> gh-1963 Fix data/source prog bar showing blue when all data is visible

CHANGELOG.md, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsDataStoreModule.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsVolumeObjectInfoProvider.java
=> gh-1971 Fix 'no appender' errors when editing a Data volume

CHANGELOG.md, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/client/ace/AceEditor.java, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/ace.js, stroom-core-client-widget/src/main/java/stroom/editor/client/view/Editor.java
=> gh-1986 Fix missing gutter icons in stepper code pane

CHANGELOG.md, stroom-core-client-widget/src/main/java/stroom/widget/dropdowntree/client/view/QuickFilterTooltipUtil.java, stroom-core-client-widget/src/main/java/stroom/widget/tooltip/client/presenter/TooltipUtil.java, stroom-util/src/main/java/stroom/util/string/StringPredicateFactory.java, stroom-util/src/test/java/stroom/util/string/TestStringPredicateFactory.java
=> gh-1990 Impove quick filter info popuo, improve word boundary matching

CHANGELOG.md, stroom-app/src/main/resources/ui/images/field.svg, stroom-app/src/main/resources/ui/images/function.svg, stroom-core-client-widget/src/main/java/stroom/svg/client/SvgPresets.java, stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/IconParentMenuItem.java, stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/MenuItemCell.java, stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/SimpleMenuItem.java, stroom-core-client-widget/src/main/resources/stroom/widget/menu/client/presenter/MenuItem.css, stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PipelineStructurePresenter.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/main/TabManager.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/ExpressionPresenter.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/ExpressionViewImpl.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/FieldsManager.java, stroom-dashboard/stroom-dashboard-client/src/main/resources/stroom/dashboard/client/table/ExpressionViewImpl.ui.xml, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataServiceImpl.java
=> Gh 1911 field picker

CHANGELOG.md, stroom-core-client/src/main/java/stroom/data/client/presenter/SourcePresenter.java, stroom-core-client/src/main/java/stroom/dictionary/client/presenter/DictionaryPresenter.java, stroom-core-client/src/main/java/stroom/pipeline/client/presenter/TextConverterPresenter.java, stroom-core-client/src/main/java/stroom/pipeline/client/presenter/XsltPresenter.java, stroom-core-client/src/main/java/stroom/xmlschema/client/presenter/XMLSchemaPresenter.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/script/client/presenter/ScriptPresenter.java
=> gh-1997 Fix missing _Format_ option on editors

CHANGELOG.md, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/selection/VolumeConfig.java, stroom-legacy/stroom-legacy-impex_6_1/src/main/java/stroom/legacy/impex_6_1/IndexDataMapConverter.java, stroom-legacy/stroom-legacy-impex_6_1/src/main/java/stroom/legacy/impex_6_1/LegacyIndexDeserialiser.java
=> Gh 2004 idx vol on legacy import

CHANGELOG.md, stroom-app/src/dist/bin/utils.sh, stroom-app/src/dist/config/scripts.env, stroom-app/src/dist/health.sh, stroom-app/src/dist/info.sh, stroom-app/src/dist/logs.sh, stroom-app/src/dist/restart.sh, stroom-app/src/dist/set_log_levels.sh, stroom-app/src/dist/start.sh, stroom-app/src/dist/status.sh, stroom-app/src/dist/stop.sh
Addresses #1866 for zip dist scripts
=> gh-1866 Change zip distribution shell scripts to execute from anywhere

CHANGELOG.md, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/GlobalConfigResourceImpl.java, stroom-node/stroom-node-api/src/main/java/stroom/node/api/NodeService.java, stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeResourceImpl.java, stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeServiceImpl.java, stroom-node/stroom-node-mock/src/main/java/stroom/node/mock/MockNodeService.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/event/PermissionChangeResourceImpl.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskResourceImpl.java
=> gh-2056 Fix HTTP method in PermissionChangeResourceImpl

stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexResourceImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexVolumeGroupResourceImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexVolumeResourceImpl.java, stroom-job/stroom-job-impl/build.gradle, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobNodeResourceImpl.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobResourceImpl.java, stroom-job/stroom-job-impl/src/test/java/stroom/job/impl/TestJobNodeResourceImpl.java
Apply Stroom standards for REST to more resources.
=> Rest resource updates

stroom-app/src/test/java/stroom/dropwizard/common/TestRestResources.java, stroom-core-shared/src/main/java/stroom/dashboard/shared/StoredQueryResource.java, stroom-dashboard/stroom-storedquery-api/src/main/java/stroom/storedquery/api/StoredQueryService.java, stroom-dashboard/stroom-storedquery-impl/build.gradle, stroom-dashboard/stroom-storedquery-impl/src/main/java/stroom/storedquery/impl/StoredQueryResourceImpl.java, stroom-dashboard/stroom-storedquery-impl/src/main/java/stroom/storedquery/impl/StoredQueryServiceImpl.java, stroom-event-logging-rs/stroom-event-logging-rs-impl/src/main/java/stroom/event/logging/rs/impl/RequestInfo.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorTaskResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/event/PermissionChangeResourceImpl.java, stroom-statistics/stroom-statistics-impl-hbase/src/main/java/stroom/statistics/impl/hbase/entity/StatsStoreResourceImpl.java, stroom-statistics/stroom-statistics-impl-hbase/src/main/java/stroom/statistics/impl/hbase/rollup/StatStoreRollupResourceImpl.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/entity/StatisticResourceImpl.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/rollup/StatisticRollupService.java, stroom-util-shared/src/main/java/stroom/util/shared/FetchWithIntegerId.java, stroom-util-shared/src/main/java/stroom/util/shared/FetchWithLongId.java, stroom-util-shared/src/main/java/stroom/util/shared/FetchWithTemplate.java, stroom-util-shared/src/main/java/stroom/util/shared/FetchWithUuid.java
Apply Stroom standards to more REST resources
=> Apply Stroom standards to more REST resources

stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/StroomIndexQueryResourceImpl.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/StroomIndexQueryService.java
Apply REST standards to StroomIndexQueryResourceImpl
=> Apply REST standards to StroomIndexQueryResourceImpl

stroom-event-logging-rs/stroom-event-logging-rs-impl/src/main/java/stroom/event/logging/rs/impl/RestResourceAutoLoggerImpl.java, stroom-event-logging-rs/stroom-event-logging-rs-impl/src/test/java/stroom/event/logging/rs/impl/TestRestResourceAutoLogger.java, stroom-event-logging/stroom-event-logging-impl/src/main/java/stroom/event/logging/impl/StroomEventLoggingServiceImpl.java, stroom-search/stroom-search-solr/src/main/java/stroom/search/solr/search/StroomSolrIndexQueryResourceImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountResourceImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/authenticate/AuthenticationResource.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/authenticate/AuthenticationResourceImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/authenticate/AuthenticationServiceImpl.java
This change provides logging for UI logins to Stroom v7
=> Additional logging for REST methods, including UI login

CHANGELOG.md, stroom-app/src/main/resources/ui/noauth/swagger/stroom.json, stroom-app/src/main/resources/ui/noauth/swagger/stroom.yaml, stroom-app/src/test/java/stroom/dropwizard/common/TestRestResources.java, stroom-core-shared/src/main/java/stroom/node/shared/NodeResource.java, stroom-core-shared/src/main/java/stroom/processor/shared/ProcessorFilterResource.java, stroom-core-shared/src/main/java/stroom/processor/shared/ProcessorResource.java, stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeResourceImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataResource.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataResourceImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterResourceImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorResourceImpl.java, stroom-ui/src/api/stroom.ts
=> Gh-2188 Autologged REST methods must return a value

CHANGELOG.md, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityFilter.java
=> Log authenticated user during noauth calls. 

CHANGELOG.md, build.gradle, stroom-legacy/stroom-legacy-db-migration/src/main/java/stroom/legacy/db/migration/V07_00_00_1502__Index.java, stroom-search/stroom-search-impl/src/test/java/stroom/search/impl/TestSearchResultCreation.java, travis.script.sh
=> gh-2203 Fix NPE in index doc partition by migration

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/destination/RollingFileDestination.java, stroom-pipeline/src/main/java/stroom/pipeline/server/writer/FileAppender.java, stroom-pipeline/src/main/java/stroom/pipeline/server/writer/LockedOutputStream.java, stroom-pipeline/src/main/java/stroom/pipeline/server/writer/RollingFileAppender.java
=> Allow file permission override for `FileAppender` and `RollingFileAppender`

CHANGELOG.md, stroom-legacy/stroom-legacy-db-migration/src/main/java/stroom/legacy/db/migration/V07_00_00_1502__Index.java
=> gh-2233 Fix null volume ID in index shard migration

CHANGELOG.md, stroom-data/stroom-data-store-impl-fs-db/build.gradle, stroom-data/stroom-data-store-impl-fs-db/src/test/java/stroom/data/store/impl/fs/db/TestFileSystemVolumeServiceImpl.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsVolumeService.java, stroom-data/stroom-data-store-util/build.gradle, stroom-data/stroom-data-store-util/src/main/java/stroom/data/store/util/ToolModule.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexVolumeServiceImpl.java, stroom-node/stroom-node-mock/src/main/java/stroom/node/mock/MockNodeInfo.java
=> gh-2261 Fix missing node name in index and fs volume stats

CHANGELOG.md, stroom-core-client-widget/src/main/java/stroom/widget/dropdowntree/client/view/QuickFilterTooltipUtil.java, stroom-util/src/main/java/stroom/util/filter/FilterFieldMappers.java, stroom-util/src/main/java/stroom/util/filter/QuickFilterPredicateFactory.java, stroom-util/src/main/java/stroom/util/filter/StringPredicateFactory.java, stroom-util/src/test/java/stroom/util/filter/QuickFilterTestBed.java, stroom-util/src/test/java/stroom/util/filter/TestQuickFilterPredicateFactory.java, stroom-util/src/test/java/stroom/util/filter/TestStringPredicateFactory.java
Fixes #2266 
Fixes #2265 
Fixes #2267
=> Gh 2267 filter prefixes

CHANGELOG.md, stroom-pipeline/src/test/java/stroom/pipeline/destination/TestRollingFileDestination.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/ElasticIndexServiceImpl.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/indexing/ElasticIndexingFilter.java
=> Elasticsearch array support

CHANGELOG.md, build.gradle, stroom-core-shared/src/main/java/stroom/search/elastic/shared/ElasticIndexFieldType.java, stroom-core-shared/src/test/java/TestElasticIndexFieldType.java, stroom-pipeline/src/test/java/stroom/pipeline/destination/TestRollingFileDestination.java, stroom-search/stroom-search-elastic/build.gradle, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/ElasticIndexServiceImpl.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/indexing/ElasticIndexingFilter.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/ElasticSearchTaskHandler.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/SearchExpressionQueryBuilder.java
=> Elasticsearch object support

CHANGELOG.md, stroom-app/build.gradle, stroom-proxy/stroom-proxy-app/build.gradle
=> gh-2293 Fix banner.txt location

stroom-app/src/main/resources/ui/css/stroom-control.css, stroom-app/src/main/resources/ui/css/valuespinner.css
=> Make `ValueSpinner` appearance consistent with other `input` elements

stroom-core-client/src/main/java/stroom/job/client/presenter/JobListPresenter.java, stroom-core-client/src/main/java/stroom/job/client/presenter/JobNodeListPresenter.java
=> Fix broken help links in `Jobs` view

stroom-app/docker/start.sh
=> Pass through CLI arguments when invoking the Docker entrypoint

CHANGELOG.md, stroom-app/docker/start.sh, stroom-app/src/main/java/stroom/app/App.java, stroom-app/src/main/java/stroom/app/commands/CreateAccountCommand.java, stroom-app/src/main/java/stroom/app/commands/CreateApiKeyCommand.java
=> Add CLI command to create an API key for a user

CHANGELOG.md, stroom-app/prod.yml.jinja2, stroom-proxy/stroom-proxy-app/proxy-prod.yml.jinja2
=> Gh 2357 remove default logging config

CHANGELOG.md, stroom-db-util/src/main/java/stroom/db/util/JooqUtil.java, stroom-explorer/stroom-explorer-api/src/main/java/stroom/explorer/api/ExplorerNodeService.java, stroom-explorer/stroom-explorer-impl-db/src/main/java/stroom/explorer/impl/db/ExplorerTreeDaoImpl.java, stroom-explorer/stroom-explorer-impl/build.gradle, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerNodeServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerTreeDao.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerTreeNode.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/MockExplorerNodeService.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaExpressionMapper.java
=> Gh 2369 reprocess sql error

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoadTaskHandler.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/AbstractRefDataStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/databases/AbstractLmdbDbTest.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/lmdb/TestBasicLmdbDb.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/lmdb/TestLmdbMaxReaders.java
=> gh-2379 Change ref LMDB to use MDB_NOTLS flag, add tests

CHANGELOG.md, stroom-cluster/stroom-cluster-lock-api/src/main/java/stroom/cluster/lock/api/ClusterLockService.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaValueDaoImpl.java
=> gh-2380 Add thread interrupt check to meta val delete job

CHANGELOG.md, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/PointIsInsideXYPolygon.java
=> Add XSLT Function pointInsideXYPolygon

CHANGELOG.md, stroom-core/src/main/java/stroom/core/receive/ReceiveDataRequestHandler.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/AttributeMapUtil.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/StandardHeaderArguments.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ForwardStreamHandler.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ProxyRequestHandler.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/FeedStatusAttributeMapFilter.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/ReceiveDataServlet.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/StroomStreamException.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/StroomStreamProcessor.java, stroom-receive/stroom-receive-common/src/test/java/stroom/receive/common/TestStroomStreamException.java, stroom-receive/stroom-receive-rules-impl/src/main/java/stroom/receive/rules/impl/DataReceiptPolicyAttributeMapFilter.java
=> gh-2448 Change log level for data receipt errors, improve log content

CHANGELOG.md, stroom-app/src/main/java/stroom/app/guice/AppModule.java, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-config/stroom-config-common/src/main/java/stroom/config/common/ConnectionPoolConfig.java, stroom-db-util/build.gradle, stroom-db-util/src/main/java/stroom/db/util/DataSourceFactoryImpl.java, stroom-db-util/src/main/java/stroom/db/util/HikariUtil.java, stroom-test-common/src/main/java/stroom/test/common/util/db/DbTestUtil.java
=> gh-2464 gh-2463 Add hikari to metrics/healthchecks, add leak config

CHANGELOG.md, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/TableRow.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/ElasticSearchTaskHandler.java
=> Display tooltip on grid cell mouse hover

CHANGELOG.md, stroom-app/src/main/java/stroom/app/App.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/App.java
=> gh-2403 Fix guice bind issues with null pathConfig

CHANGELOG.md, stroom-event-logging-rs/stroom-event-logging-rs-impl/src/main/java/stroom/event/logging/rs/impl/RequestEventLogImpl.java, stroom-event-logging/stroom-event-logging-api/src/main/java/stroom/event/logging/api/StroomEventLoggingUtil.java, stroom-event-logging/stroom-event-logging-impl/src/main/java/stroom/event/logging/impl/BulkActionResultObjectInfoProvider.java, stroom-event-logging/stroom-event-logging-impl/src/main/java/stroom/event/logging/impl/EventLoggingModule.java, stroom-event-logging/stroom-event-logging-mock/src/main/java/stroom/event/logging/mock/MockStroomEventLoggingModule.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerResourceImpl.java, stroom-meta/stroom-meta-impl-db/build.gradle, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-meta/stroom-meta-impl-db/src/test/java/stroom/meta/impl/db/TestMetaServiceImpl.java, stroom-meta/stroom-meta-impl-db/src/test/java/stroom/meta/impl/db/TestMetaValueDaoImpl.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaResourceImpl.java
=> Gh 2240 and gh 2241 logging fixes

stroom-db-util/src/main/java/stroom/db/util/CommonExpressionMapper.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-security/stroom-security-identity-db/src/main/java/stroom/security/identity/db/AccountDaoImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountDao.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountResource.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountResourceImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountResultPage.java, stroom-util/src/main/java/stroom/util/filter/QuickFilterPredicateFactory.java, stroom-util/src/test/java/stroom/util/filter/TestQuickFilterPredicateFactory.java, unreleased_changes/20211029_172130_471__2532.md
=> Gh 2532 logging quickfilter

stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnv.java, stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnvFactory.java, unreleased_changes/20211102_103430_655__2541.md
=> gh-2541 Stop finished queries from deleting all LMDB env

stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/authenticate/AuthenticationServiceImpl.java, unreleased_changes/20211102_180915_780__2533.md
=> Gh 2533 logout npe

stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerSessionImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerTreeModel.java, stroom-util/src/main/java/stroom/util/servlet/HttpServletRequestHolder.java, unreleased_changes/20211103_095942_028__2530.md
=> gh-2530 Ensure session is available in ExplorerSessionImpl

stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/LmdbDataStoreFactory.java, stroom-search/stroom-search-impl/src/test/java/stroom/search/impl/TestSearchResultCreation.java, unreleased_changes/20211104_205217_622__2548.md
=> gh-2548 Clear contents of search lmdb localDir on boot

stroom-config/stroom-config-app/src/main/java/stroom/config/app/AppConfigModule.java, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-config/stroom-config-global-impl/src/test/java/stroom/config/global/impl/TestConfigMapper.java, stroom-lmdb/src/main/java/stroom/lmdb/LmdbConfig.java, stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnvFactory.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataConfig.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLmdbConfig.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestReferenceDataLmdbConfig.java, stroom-query/stroom-query-common/build.gradle, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/LmdbDataStore.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/ResultStoreConfig.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/ResultStoreLmdbConfig.java, stroom-query/stroom-query-common/src/test/java/stroom/query/common/v2/TestResultStoreLmdbConfig.java, unreleased_changes/20211105_105736_517__2549.md
=> gh-2549 Refactor lmdb config into two concrete classes

stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/LmdbDataStore.java, unreleased_changes/20211115_162850_923__2553.md
=> gh-2553 Syncronise get() and clear(). Add env.isClosed() check.

stroom-meta/stroom-meta-impl-db/src/test/java/stroom/meta/impl/db/TestMetaDaoImpl.java
=> gh-2563 Make TestMetaDaoImpl.testFind dynamic

stroom-core-client/src/main/java/stroom/task/client/presenter/TaskManagerListPresenter.java, stroom-core-client/src/main/java/stroom/task/client/presenter/TaskProgressUtil.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskManagerImpl.java, unreleased_changes/20211116_141442_455__2555.md
=> gh-2555 Remove checkbox from dead server tasks

stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, unreleased_changes/20211214_171243_128__2647.md
=> gh-2647 Fix `Unrecognised permission assigned` error in logs

stroom-feed/stroom-feed-impl/src/main/java/stroom/feed/impl/FeedNameValidator.java, stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ContentServiceImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardWriterCacheImpl.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobBootstrap.java, stroom-kafka/stroom-kafka-impl/src/main/java/stroom/kafka/impl/KafkaConfigStoreImpl.java, stroom-lmdb/src/main/java/stroom/bytebuffer/ByteBufferPoolImpl4.java, stroom-pipeline/src/main/java/stroom/pipeline/destination/RollingDestinations.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorTaskManagerImpl.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ForwardStreamHandlerFactory.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/handler/TestProxyHandlerFactory.java, stroom-proxy/stroom-proxy-repo/src/main/java/stroom/proxy/repo/ProxyRepositoryStreamHandlerFactory.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/shard/IndexShardSearcherCacheImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/AuthenticationService.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/ResolvedOpenIdConfig.java, stroom-servicediscovery/stroom-servicediscovery-impl/src/main/java/stroom/servicediscovery/impl/ServiceDiscoveryManager.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticAggregationTransactionHelper.java, stroom-statistics/stroom-statistics-impl/src/main/java/stroom/statistics/impl/InternalStatisticsReceiverImpl.java, stroom-statistics/stroom-statistics-impl/src/main/java/stroom/statistics/impl/MultiServiceInternalStatisticsReceiver.java, stroom-statistics/stroom-statistics-impl/src/test/java/stroom/statistics/impl/TestMultiServiceInternalStatisticsReceiver.java, stroom-util/src/main/java/stroom/util/io/HomeDirProviderImpl.java, stroom-util/src/main/java/stroom/util/io/TempDirProviderImpl.java, unreleased_changes/20211216_143045_221__2657.md
=> gh-2657 Use Providers for config in @Singleton classes

stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, unreleased_changes/20211215_095701_701__2648.md
=> gh-2648 Add error message to data viewer when ID is invalid

stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/ConfigProvidersModule.java, stroom-config/stroom-config-global-impl/src/test/java/stroom/config/global/impl/GenerateConfigProvidersModule.java, stroom-config/stroom-config-global-impl/src/test/java/stroom/config/global/impl/TestConfigProvidersModule.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/HttpClientTlsConfig.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/guice/ProxyConfigProvidersModule.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ForwardDestinationConfig.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ForwardStreamHandler.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/TestProxyConfigModule.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/guice/GenerateProxyConfigProvidersModule.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/guice/TestProxyConfigProvidersModule.java, stroom-util/src/main/java/stroom/util/cert/SSLConfig.java, stroom-util/src/main/java/stroom/util/yaml/YamlUtil.java, unreleased_changes/20211216_173126_112__0.md
=> Gh 2659 proxy config errors

stroom-core-client/src/main/java/stroom/data/client/presenter/MarkerListPresenter.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoadTaskHandler.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/RefStreamDefinition.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, unreleased_changes/20211220_191545_566__2666.md, unreleased_changes/20211221_115251_849__0.md
=> Gh 2666 ref missing strm

stroom-core/src/main/java/stroom/core/receive/DataStoreFileSetProcessor.java, unreleased_changes/20211221_161947_923__2644.md
=> gh-2644 Make proxy agg break out of fileset loop on ex

build.gradle, stroom-query/stroom-expression/build.gradle, stroom-query/stroom-expression/src/main/java/stroom/dashboard/expression/v1/ExpressionParser.java, stroom-query/stroom-expression/src/main/java/stroom/dashboard/expression/v1/ExpressionTokeniser.java, stroom-query/stroom-expression/src/main/java/stroom/dashboard/expression/v1/Negate.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/AbstractExpressionParserTest.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/QuadList.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/TestExpressionParser.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/TestExpressionParserAggregates.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/TestExpressionParserLinks.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/TestExpressionParserSelections.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/TestExpressionParserUris.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/TestExpressionTokeniser.java, stroom-test-common/src/test/java/stroom/test/common/util/test/TestTempDirExtension.java, stroom-util/src/main/java/stroom/util/functions/QuadConsumer.java, stroom-util/src/main/java/stroom/util/functions/QuadFunction.java, stroom-util/src/main/java/stroom/util/functions/TriConsumer.java, stroom-util/src/main/java/stroom/util/functions/TriFunction.java, unreleased_changes/20211222_213320_987__2650.md
=> gh-2650 Fix expr parser handling of negation

stroom-meta/stroom-meta-impl-db/src/main/resources/stroom/meta/impl/db/migration/V07_00_00_010__meta_processor_pipeline_uuid_index.sql, stroom-meta/stroom-meta-impl-db/src/main/resources/stroom/meta/impl/db/migration/afterMigrate__01_drop_mig_sprocs.sql, stroom-meta/stroom-meta-impl-db/src/main/resources/stroom/meta/impl/db/migration/beforeMigrate__01_create_mig_sprocs.sql, unreleased_changes/20220104_114546_975__2679.md
Fixes #2679 
While the lack of this index may not be the problem it seems sensible to add it anyway.
=> gh-2679 Add unique index on `meta_processor.pipeline_uuid`

stroom-core-client-widget/src/main/java/stroom/editor/client/view/Editor.java, unreleased_changes/20220104_151238_854__2596.md
=> gh-2596 Disable the Ace editor settings menu

stroom-core-shared/src/main/java/stroom/search/elastic/shared/ElasticIndexFieldType.java, stroom-core-shared/src/test/java/TestElasticIndexFieldType.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/ElasticIndexServiceImpl.java, stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/ElasticSearchFactory.java
=> Fix Elasticsearch query returning no search results

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-lmdb/src/main/java/stroom/bytebuffer/ByteBufferPoolConfig.java, stroom-lmdb/src/main/java/stroom/bytebuffer/ByteBufferPoolFactory.java, stroom-lmdb/src/main/java/stroom/bytebuffer/ByteBufferPoolImpl4.java, stroom-lmdb/src/main/java/stroom/bytebuffer/ByteBufferSupport.java, stroom-lmdb/src/main/java/stroom/bytebuffer/PooledByteBuffer.java, stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnv.java, stroom-lmdb/src/test/java/stroom/bytebuffer/TestByteBufferPool.java, stroom-lmdb/src/test/java/stroom/bytebuffer/TestByteBufferPoolImpl4.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, unreleased_changes/20220107_163527_441__2696.md
=> Gh 2696 buffer pool blocking

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-config/stroom-config-global-impl-db/src/main/resources/stroom/config/global/impl/db/migration/V07_00_00_002__update_meta_types_prop.sql, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/ConfigMapper.java, stroom-config/stroom-config-global-impl/src/test/java/stroom/config/global/impl/TestConfigMapper.java, stroom-core-shared/src/main/java/stroom/data/shared/StreamTypeNames.java, stroom-core/src/main/java/stroom/core/query/SuggestionsServiceImpl.java, stroom-core/src/main/java/stroom/core/receive/ReceiveDataRequestHandler.java, stroom-data/stroom-data-store-impl-fs-db/src/main/java/stroom/data/store/impl/fs/db/FsTypePathDaoImpl.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaTypeDaoImpl.java, stroom-meta/stroom-meta-impl/build.gradle, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaServiceConfig.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaServiceImpl.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ProxyRequestConfig.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ProxyRequestHandler.java, stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/AttributeMapValidator.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/StroomStreamException.java, stroom-util-shared/src/main/java/stroom/util/shared/validation/IsSupersetOf.java, stroom-util-shared/src/main/java/stroom/util/shared/validation/IsSupersetOfValidator.java, stroom-util/build.gradle, stroom-util/src/main/java/stroom/util/validation/IsSubsetOfValidatorImpl.java, stroom-util/src/main/java/stroom/util/validation/IsSupersetOfValidatorImpl.java, stroom-util/src/main/java/stroom/util/validation/ValidationModule.java, stroom-util/src/test/java/stroom/util/validation/TestIsSupersetOfValidatorImpl.java, unreleased_changes/20220106_144055_233__2688.md, unreleased_changes/20220106_144630_557__2688.md
=> gh-2688 Add all known strm types to metaTypes config default

stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/ElasticSearchTaskHandler.java
=> Only use ES search slices if the number of slices is greater than 1

stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/search/ElasticSearchTaskHandler.java
=> Do not recycle ES `Scroll` request across threads

stroom-core-client/src/main/java/stroom/processor/client/presenter/ProcessorPresenter.java
=> Fix invalid REST method return type

stroom-core-shared/src/main/java/stroom/meta/shared/MetaExpressionUtil.java, stroom-db-util/src/main/java/stroom/db/util/TermHandler.java, unreleased_changes/20220123_150943_281__2730.md
=> Fix folder presenter Processors tab always being empty

stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, unreleased_changes/20220128_125408_984__2736.md
=> gh-2736 Fix missing or wrongly appearing meta/context tab

stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorTaskDaoImpl.java, unreleased_changes/20220128_170227_713__2732.md
=> gh-2732 Fix bug when opening active tasks tab for an empty folder

stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceData.java, unreleased_changes/20220207_144546_532__2757.md
=> gh-2757 Make ref load throw when a strm previously failed

stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/ProxyConfig.java, stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml, unreleased_changes/20220207_152453_462__2753.md
=> gh-2753 Change default proxy config useDefaultOpenIdCredentials=false

stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaModule.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorModule.java, unreleased_changes/20220207_155750_377__2761.md
=> gh-2761 Fix job descriptions

stroom-event-logging/stroom-event-logging-impl/src/main/java/stroom/event/logging/impl/StroomEventLoggingServiceImpl.java, unreleased_changes/20220222_162517_046__2786.md
=> gh-2786 Handle multiple IPs in X-FORWARDED-FOR header

stroom-app/src/main/java/stroom/app/BootstrapUtil.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/GlobalConfigBootstrapService.java, stroom-db-util/src/main/java/stroom/db/util/AbstractDataSourceProviderModule.java, stroom-db-util/src/main/java/stroom/db/util/AbstractFlyWayDbModule.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaTypeDaoImpl.java, stroom-util/src/main/java/stroom/util/BuildInfoProvider.java, stroom-util/src/main/java/stroom/util/db/DbMigrationState.java, unreleased_changes/20220303_182542_677__0.md, unreleased_changes/20220303_183000_188__2799.md
=> Gh 2799 meta types npe

stroom-core-client/src/main/java/stroom/index/client/presenter/IndexVolumeEditPresenter.java, unreleased_changes/20220308_174212_479__2807.md
=> gh-2807 Change IndexVolumeEditPresenter to show all nodes

.idea/runConfigurations/Stroom__no_superdev_.xml, stroom-core-client/src/main/java/stroom/alert/client/view/CommonAlertViewImpl.java, stroom-core-client/src/main/resources/stroom/alert/client/view/alert.css, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/query/QueryPresenter.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/SearchRequestMapper.java, stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnv.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/FlatResultCreator.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/TableResultCreator.java, unreleased_changes/20220310_114958_119__0.md, unreleased_changes/20220310_115034_075__0.md, unreleased_changes/20220310_115544_289__2806.md
=> Gh 2806 no viz defined

stroom-app/src/main/resources/ui/noauth/swagger/stroom.json, stroom-app/src/main/resources/ui/noauth/swagger/stroom.yaml, stroom-core-client-widget/src/main/java/stroom/editor/client/view/EditorViewImpl.java, stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, stroom-core-shared/src/main/java/stroom/meta/shared/MetaResource.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataFetcher.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaResourceImpl.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/SearchableDual.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskModule.java, stroom-ui/src/api/stroom.ts, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20220311_110104_165__0.md, unreleased_changes/20220311_112921_094__2810.md
=> Gh 2810 data link err strms

stroom-data/stroom-data-retention-api/src/main/java/stroom/data/retention/api/DataRetentionCreationTimeUtil.java, stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionPolicyExecutor.java, stroom-data/stroom-data-retention-impl/src/test/java/stroom/data/retention/impl/TestDataRetentionPolicyExecutor.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-meta/stroom-meta-impl-db/src/test/java/stroom/meta/impl/db/TestMetaServiceImpl.java, unreleased_changes/20220318_204747_129__2817.md
=> Fix data retention summary counts

stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, stroom-pipeline/src/main/java/stroom/pipeline/reader/ByteStreamDecoder.java, unreleased_changes/20220413_152534_162__2816.md
=> gh-2816 Fix missing part nav controls for binary multi part data

stroom-app/src/main/java/stroom/app/commands/ManageUsersCommand.java, stroom-app/src/test/java/stroom/db/util/TestGenericDao.java, stroom-app/src/test/java/stroom/explorer/TestExplorerTreePerformance.java, stroom-app/src/test/java/stroom/meta/impl/TestMetaSecurityFilter.java, stroom-app/src/test/java/stroom/meta/impl/TestMetaService.java, stroom-app/src/test/java/stroom/test/MockServiceModule.java, stroom-app/src/test/java/stroom/test/SampleDataGenerator.java, stroom-app/src/test/java/stroom/test/SetupSampleDataBean.java, stroom-core-shared/src/main/java/stroom/security/shared/Changes.java, stroom-db-util/src/main/java/stroom/db/util/GenericDao.java, stroom-db-util/src/main/java/stroom/db/util/JooqUtil.java, stroom-security/stroom-security-impl-db/src/main/java/stroom/security/impl/db/DocumentPermissionDaoImpl.java, stroom-security/stroom-security-impl-db/src/main/java/stroom/security/impl/db/UserDaoImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/TestAppPermissionServiceImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/TestDocumentPermissionsServiceImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/TestUserServiceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocumentPermissionDao.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocumentPermissionServiceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserDao.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserService.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserServiceImpl.java, unreleased_changes/20220408_172649_308__2830.md, unreleased_changes/20220412_154657_940__2830.md, unreleased_changes/20220412_155321_866__2830.md
=> gh-2830 Fix invalid event XML logged when removing a perm

stroom-core-client-widget/src/main/java/stroom/editor/client/model/XmlFormatter.java, stroom-core-client/src/test/java/stroom/widget/editor/testclient/model/TestXmlFormatter.java, stroom-core-client/src/test/resources/TestXmlFormatter/TestComments.in, stroom-core-client/src/test/resources/TestXmlFormatter/TestComments.out, stroom-core-client/src/test/resources/TestXmlFormatter/TestComments.tmp, unreleased_changes/20220408_170031_582__2827.md
=> gh-2827 Fix Format when comment contains unmatched double quote

stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20220422_091547_292__2839.md
=> PR for #2839 - Invalid XML is generated when Permissions are initially added to a User

stroom-security/stroom-security-identity-db/src/main/java/stroom/security/identity/db/AccountDaoImpl.java, stroom-security/stroom-security-identity-db/src/main/java/stroom/security/identity/db/PasswordHashUtil.java, stroom-security/stroom-security-identity-db/src/main/java/stroom/security/identity/db/TokenDaoImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountResourceImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/token/TokenResource.java, stroom-ui/src/components/Account/AccountManager/useColumns.tsx, stroom-ui/src/components/Account/TokenManager/useColumns.ts, stroom-util-shared/src/main/java/stroom/util/shared/CompareUtil.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20220422_134939_635__2843.md, unreleased_changes/20220422_135631_460__0.md, unreleased_changes/20220422_140046_698__2840.md, unreleased_changes/20220422_153817_296__2841.md, unreleased_changes/20220422_153859_957__0.md
Fixes #2840
Fixes #2843
Fixes #2841
=> PR for #2840 - Manage Accounts screen generates  SQL error

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-core-client/src/main/java/stroom/instance/client/ClientApplicationInstance.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/UiConfig.java, stroom-dashboard/stroom-dashboard-impl/build.gradle, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/ActiveQueries.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/ActiveQuery.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/ApplicationInstance.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/ApplicationInstanceManager.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/ApplicationInstanceWebSocket.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/DashboardConfig.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/DashboardModule.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/StreamTypeExtensions.java, stroom-dropwizard-common/src/main/java/stroom/dropwizard/common/WebSockets.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/shard/IndexShardSearchTaskHandler.java, unreleased_changes/20220427_092853_397__2838.md
=> PR for #2838 - Various WebSocket issues when using ALB

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-index/stroom-index-app/src/test/java/stroom/index/impl/TestIndexShardIO.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardWriterCacheImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardWriterImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexWriterConfig.java, unreleased_changes/20220429_121419_779__2855.md
=> PR for #2855 - IndexShardWriterImpl.java has a hardcoded limit of 1s before WARNing of a slow addDocument() call

build.gradle, stroom-event-logging/stroom-event-logging-impl/src/main/java/stroom/event/logging/impl/StroomEventLoggingServiceImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardWriterImpl.java, unreleased_changes/20220503_094951_820__2856.md
=> PR for #2856 - Call to /api/systemInfo from host generates bad XML

stroom-core-client/src/main/java/stroom/data/client/view/CharacterNavigatorViewImpl.java, stroom-core-client/src/main/java/stroom/data/client/view/ItemNavigatorViewImpl.java, unreleased_changes/20220503_183313_138__2863.md
=> PR for #2863 - UI locks up if you quickly page forward a multi-part Raw Events stream

stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardWriterImpl.java, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/ExtractionDecorator.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/ClusterSearchTaskHandler.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/shard/IndexShardHitCollector.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/shard/IndexShardSearchFactory.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/shard/IndexShardSearchTaskHandler.java, stroom-search/stroom-search-solr/src/main/java/stroom/search/solr/search/SolrClusterSearchTaskHandler.java, stroom-search/stroom-search-solr/src/main/java/stroom/search/solr/search/SolrSearchFactory.java, stroom-search/stroom-search-solr/src/main/java/stroom/search/solr/search/Tracker.java, stroom-task/stroom-task-api/src/main/java/stroom/task/api/TaskContext.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskContextImpl.java, unreleased_changes/20220519_172144_292__2874.md
=> PR for #2874 - Exception thrown for Index shard.

stroom-core/src/main/java/stroom/core/dataprocess/PipelineDataProcessorTaskExecutor.java, stroom-db-util/src/main/java/stroom/db/util/JooqUtil.java, stroom-pipeline/src/main/java/stroom/pipeline/PipelineStoreImpl.java, stroom-processor/stroom-processor-api/src/main/java/stroom/processor/api/ProcessorService.java, stroom-processor/stroom-processor-impl-db/build.gradle, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorFilterDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorTaskDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/TestProcessorDaoImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/DataProcessorTaskHandler.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/MockProcessorDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/MockProcessorFilterDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorServiceImpl.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20220527_174633_100__2889.md
=> PR for #2889 - Orphaned proc filter when pipeline is deleted in the UI

stroom-pipeline/src/main/java/stroom/pipeline/destination/RollingDestinations.java, unreleased_changes/20220622_151048_277__2906.md
=> gh-2906 Fix RollingStreamAppender failing to roll on timed basis

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsPathHelper.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsSource.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsVolumeConfig.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/StreamTypeExtensions.java, stroom-data/stroom-data-store-impl-fs/src/test/java/stroom/data/store/impl/fs/TestFileSystemUtil.java, stroom-data/stroom-data-store-impl-fs/src/test/java/stroom/data/store/impl/fs/TestStreamTypeExtensions.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaServiceConfig.java, unreleased_changes/20220622_150254_289__2900.md
=> Gh 2900 strm tp ext

stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, unreleased_changes/20220623_120037_646__2192.md
=> PR for #2912 - Prevent feed rename

stroom-pipeline/src/main/java/stroom/pipeline/destination/RollingDestinations.java, unreleased_changes/20220624_101230_939__2906.md
=> PR for #2906 - RollingDestination trying to roll stream destinations outside of a user context

stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnv.java, stroom-util/src/main/java/stroom/util/concurrent/UncheckedInterruptedException.java, unreleased_changes/20220624_105046_980__2916.md
=> PR for #2916 - Seeing `Error putting key <nnnn> into map <XYZ>: Thread interrupted while waiting for write lock`

stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaValueDaoImpl.java
=> PR for #2925 - Attribute Value Data Retention Job taking a long time

stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/HttpCall.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/HttpClientCache.java, stroom-util/src/main/java/stroom/util/config/OkHttpClientConfig.java, stroom-util/src/main/java/stroom/util/sysinfo/HasSystemInfo.java, unreleased_changes/20220629_122517_177__2933.md
=> PR for #2933 - Getting error with `HTTP_1_1_REQUIRED` when using `http-call` xslt func

stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/TablePresenter.java, unreleased_changes/20220629_210051_317__2938.md
=> PR for #2938 - Querying Annotations Datasource gives error

stroom-app/src/test/java/stroom/statistics/impl/sql/TestSQLStatisticAggregationManager.java, stroom-app/src/test/java/stroom/statistics/impl/sql/TestSQLStatisticFlushTaskHandler.java, stroom-app/src/test/java/stroom/statistics/impl/sql/TestStatisticsQueryServiceImpl.java, stroom-app/src/test/java/stroom/test/AbstractStatisticsCoreIntegrationTest.java, stroom-app/src/test/java/stroom/test/StatisticsCoreTestModule.java, stroom-app/src/test/java/stroom/test/StatisticsTestDbConnectionsModule.java, stroom-app/src/test/resources/logback-test.xml, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/ConnectionUtil.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticAggregationTransactionHelper.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticCacheImpl.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticEventStore.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticFlushTaskHandler.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticValueBatchSaveService.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticValueBatchSaveServiceTestDatabaseTool.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticsConfig.java, stroom-statistics/stroom-statistics-impl-sql/src/main/resources/stroom/statistics/impl/sql/db/migration/R__sql_statistics_stored_procedures.sql, stroom-statistics/stroom-statistics-impl-sql/src/main/resources/stroom/statistics/impl/sql/db/migration/R__sql_statistics_views.sql, stroom-statistics/stroom-statistics-impl-sql/src/main/resources/stroom/statistics/impl/sql/db/migration/V07_00_00_002__Remove_processing_flag.sql, stroom-statistics/stroom-statistics-impl-sql/src/main/resources/stroom/statistics/impl/sql/db/migration/beforeMigrate__create_mig_sprocs.sql, stroom-statistics/stroom-statistics-impl-sql/src/test/java/stroom/statistics/impl/sql/TestSQLStatisticEventStore.java, stroom-test-common/src/main/java/stroom/test/common/util/db/DbTestUtil.java, stroom-util/src/main/java/stroom/util/logging/LogExecutionTime.java, unreleased_changes/20220701_111901_177__2946.md, unreleased_changes/20220701_111938_690__2946.md, unreleased_changes/20220704_160445_012__2946.md
=> PR for #2946 - Lock wait timeout for SQL statistics

stroom-app/src/test/java/stroom/statistics/impl/sql/TestSQLStatisticAggregationManager.java, stroom-app/src/test/java/stroom/statistics/impl/sql/TestSQLStatisticFlushTaskHandler.java, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticAggregationManager.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticAggregationTransactionHelper.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticFlushTaskHandler.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/SQLStatisticsConfig.java, stroom-statistics/stroom-statistics-impl-sql/src/main/resources/stroom/statistics/impl/sql/db/migration/R__sql_statistics_stored_procedures.sql, stroom-statistics/stroom-statistics-impl-sql/src/main/resources/stroom/statistics/impl/sql/db/migration/V07_00_00_003__Improve_stage2_aggregation.sql, stroom-statistics/stroom-statistics-impl-sql/src/test/java/stroom/statistics/impl/sql/TestSQLStatisticAggregationTransactionHelper.java, unreleased_changes/20220708_233057_246__2966.md
=> PR for #2966 - Split stage 2 stats aggregation into batches

stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnv.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataConfig.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLmdbConfig.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/databases/KeyValueStoreDb.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/databases/RangeStoreDb.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/TestRefDataOffHeapStore.java, unreleased_changes/20220621_101711_763__2897.md
=> Gh 2897 ref load purge issues

stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/MapDataStore.java, unreleased_changes/20220712_155448_908__2981.md
=> Terminate on-heap searches once result limit is reached

stroom-app/src/main/java/stroom/app/BootstrapUtil.java, unreleased_changes/20220712_160922_652__2978.md
=> PR for #2978 - Lock Wait Timeouts when upgrading to b.217

stroom-app/src/test/java/stroom/job/api/TestSchedule.java, stroom-job/stroom-job-api/src/main/java/stroom/job/api/Schedule.java, stroom-job/stroom-job-api/src/main/java/stroom/job/api/ScheduledJob.java, stroom-lmdb/src/main/java/stroom/lmdb/AbstractLmdbDb.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataConfig.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/RefDataStoreModule.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/serdes/RefDataProcessingInfoSerde.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/TestRefDataOffHeapStore.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/serdes/TestRefDataProcessingInfoSerde.java, unreleased_changes/20220715_145252_314__2984.md
=> PR for #2984 - Ref store purge of partial loads on boot preventing node ping response

stroom-index/stroom-index-impl-db/src/main/resources/stroom/index/impl/db/migration/R__index_views.sql, stroom-index/stroom-index-impl-db/src/main/resources/stroom/index/impl/db/migration/V07_00_00_004__index_shard_drop_old_index_id_col.sql, unreleased_changes/20220719_090615_767__2995.md
=> PR for #2995 - 7.0.0 DB Migration failing

stroom-pipeline/src/main/java/stroom/pipeline/state/MetaHolder.java, unreleased_changes/20220720_133323_842__3001.md
=> PR for #3001 - Stepping context stream shows raw events rather context sub-stream in source pane

stroom-db-util/src/main/java/stroom/db/util/JooqUtil.java, unreleased_changes/20220808_100846_631__3018.md
=> PR for #3018 - UI error triangle.. class java.sql.SQLException cannot be cast to class java.lang.InterruptedException

stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataFetcher.java, unreleased_changes/20220808_115048_496__3011.md
=> PR for #3011 - Test Window is truncating events for display, but this causes failures when using a Display pipeline

stroom-core-client-widget/src/main/java/stroom/editor/client/model/XmlFormatter.java, stroom-core-client/src/test/java/stroom/widget/editor/testclient/model/TestXmlFormatter.java, stroom-util/src/main/java/stroom/util/io/DiffUtil.java, unreleased_changes/20220809_111537_729__2867.md
=> PR for #2867 - Data Preview Being Too Clever When It Thinks It Sees XML

stroom-core-client/src/main/java/stroom/data/client/presenter/ClassificationWrappedMetaPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/MetaPresenter.java, stroom-core-client/src/main/java/stroom/feed/client/presenter/FeedPresenter.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataFetcher.java, stroom-feed/stroom-feed-impl/src/main/java/stroom/feed/impl/FeedDocCache.java, stroom-feed/stroom-feed-impl/src/main/java/stroom/feed/impl/FeedModule.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20220816_115634_444__0.md, unreleased_changes/20220816_120608_759__3028.md
=> PR for #3028 - Changing a feed's charset not being reflected in data preview pane

stroom-core-shared/src/main/java/stroom/index/shared/IndexShard.java, stroom-index/stroom-index-impl-db/src/main/java/stroom/index/impl/db/IndexShardDaoImpl.java, stroom-index/stroom-index-impl-db/src/test/java/stroom/index/impl/db/TestModule.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexModule.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardDao.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardFields.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardServiceImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorTaskDaoImpl.java, unreleased_changes/20220809_170739_088__3014.md
=> PR for #3014 - Expose Index Shard info via Meta Store

gradle.properties, stroom-docstore/stroom-docstore-impl/src/main/java/stroom/docstore/impl/StoreImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/cache/AbstractDocPool.java, stroom-pipeline/src/main/java/stroom/pipeline/cache/AbstractPoolCache.java, stroom-pipeline/src/main/java/stroom/pipeline/cache/ParserFactoryPoolImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/cache/PipelineCacheModule.java, stroom-pipeline/src/main/java/stroom/pipeline/cache/PoolKey.java, stroom-pipeline/src/main/java/stroom/pipeline/cache/SchemaPoolImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/cache/XsltPoolImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/EffectiveStreamCache.java, stroom-util/src/main/java/stroom/util/entityevent/EntityEvent.java, stroom-util/src/main/java/stroom/util/logging/LambdaLogger.java, unreleased_changes/20220810_133129_347__3016.md, unreleased_changes/20220810_153455_609__0.md
=> PR for #3016 - Imported XSLT changes not being updated when pipeline saved

stroom-processor/stroom-processor-impl-db/src/main/resources/stroom/processor/impl/db/migration/V07_00_02_001__processor_task_idx.sql, unreleased_changes/20220816_124122_132__3027.md
=> PR for #3027 - Lots of slow query warnings for old task deletion

stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, unreleased_changes/20220913_095643_497__3048.md
=> PR for #3048 - Feed Copy/Rename Changes

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-pipeline/src/main/java/stroom/pipeline/refdata/EffectiveStreamCache.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataConfig.java, unreleased_changes/20220913_162501_390__3052.md
=> PR for #3052 - Effective Stream Cache is configured by default to use TTI , please use TTL

stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataServiceImpl.java, unreleased_changes/20220914_131339_780__3051.md
=> PR for #3051 - Ref Data Purge API is sequentially processing each node

stroom-app/src/main/resources/ui/noauth/swagger/stroom.json, stroom-app/src/main/resources/ui/noauth/swagger/stroom.yaml, stroom-pipeline/src/main/java/stroom/pipeline/reader/InvalidXMLCharFilterReaderElement.java, stroom-pipeline/src/main/java/stroom/pipeline/reader/InvalidXmlCharFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/reader/Xml10Chars.java, stroom-pipeline/src/main/java/stroom/pipeline/reader/Xml11Chars.java, stroom-pipeline/src/main/java/stroom/pipeline/reader/XmlChars.java, stroom-pipeline/src/test/java/stroom/pipeline/reader/TestBadTextXMLFilterReader.java, stroom-pipeline/src/test/java/stroom/pipeline/reader/TestFindReplaceFilter2.java, stroom-pipeline/src/test/java/stroom/pipeline/reader/TestInvalidXmlCharReplacementFilter.java, stroom-pipeline/src/test/java/stroom/pipeline/reader/TestXml11Chars.java, stroom-statistics/stroom-statistics-impl-sql/src/test/java/stroom/statistics/impl/sql/TestMySQLCharacterSets.java, stroom-ui/generateApi.sh, stroom-ui/package.json, stroom-ui/src/api/stroom.ts, stroom-ui/src/stroom.ts, stroom-ui/swagger_typescript_api_root/package-lock.json, stroom-ui/swagger_typescript_api_root/package.json, stroom-util/src/main/java/stroom/util/xml/MyXmlEmitter.java, unreleased_changes/20220915_173718_800__3057.md
=> gh-3057 Change InvalidXmlCharFilterReader to filter out restricted control chars

build.gradle, stroom-config/stroom-config-app/build.gradle, stroom-dashboard/stroom-dashboard-impl/build.gradle, stroom-lmdb/build.gradle, unreleased_changes/20221020_113312_569__3078.md
=> PR for #3078 - CVE-2922-42889 in apache commons-text

stroom-app/src/main/resources/ui/noauth/swagger/stroom.json, stroom-app/src/main/resources/ui/noauth/swagger/stroom.yaml, stroom-core-client/src/main/java/stroom/query/client/ExpressionModel.java, stroom-core-client/src/main/java/stroom/query/client/TermEditor.java, stroom-query/stroom-query-api/build.gradle, stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/ExpressionTerm.java, stroom-test-common/src/main/java/stroom/test/common/DynamicTestBuilder.java, stroom-ui/src/api/stroom.ts, stroom-util-shared/src/main/java/stroom/util/shared/StringUtil.java, stroom-util-shared/src/test/java/stroom/util/shared/TestStringUtil.java, stroom-util/src/main/java/stroom/util/filter/QuickFilterPredicateFactory.java, stroom-util/src/test/java/stroom/util/filter/TestQuickFilterPredicateFactory.java, unreleased_changes/20221116_110829_972__0.md, unreleased_changes/20221116_115051_426__3111.md
=> PR for #3111 - Stream Filters coping with trailing spaces

stroom-config/stroom-config-app/src/main/java/stroom/config/app/SuperDevUtil.java, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/ContentSecurityConfig.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/ContentSecurityFilter.java, unreleased_changes/20221013_191102_768__3066.md
=> PR for #3066 - Set Strict-Transport-Security header in HTTPS web server

stroom-app/src/test/java/stroom/pipeline/refdata/TestReferenceData.java, stroom-app/src/test/java/stroom/pipeline/refdata/TestReferenceDataWithCache.java, stroom-docref/src/main/java/stroom/docref/DocRef.java, stroom-pipeline/src/main/java/stroom/pipeline/errorhandler/ErrorReceiver.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/LookupIdentifier.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/RefDataLoaderHolder.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/RefDataLookupRequest.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/RefDataStoreHolder.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceData.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoadTaskHandler.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataResult.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataServiceImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/MultiRefDataValueProxy.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/RefDataValueProxy.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/RefStreamDefinition.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/SingleRefDataValueProxy.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/AbstractLookup.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/BitmapLookup.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/Lookup.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestEffectiveStreamCache.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestRefDataStoreHolder.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestReferenceDataFilter.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestReferenceDataResult.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/TestMultiRefDataValueProxy.java, stroom-util-shared/src/main/java/stroom/util/shared/StringUtil.java, unreleased_changes/20221214_181051_146__3136.md
Fixes #3136, well, speculatively.
=> PR for #3136 - Seeing `No effective streams found` errors when a ref data map contains XML data

stroom-core-client/src/main/java/stroom/cache/client/presenter/CacheListPresenter.java, stroom-core-client/src/main/java/stroom/cache/client/presenter/CacheNodeListPresenter.java, unreleased_changes/20221219_233904_750__3127.md
=> PR for #3127 - Clearing cache item triggers a `ClassCastException` error

stroom-core-client/src/main/java/stroom/importexport/client/presenter/DependenciesPresenter.java, stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/DependencyServiceImpl.java, unreleased_changes/20221219_231921_377__3148.md
=> PR for #3148 - Dependencies screen incorrectly showing queries against Dual and Reference Data as Missing status

stroom-ui/src/components/Account/EditToken/CreateToken.tsx, unreleased_changes/20221220_183119_682__3145.md
=> PR for #3145 - New 7.1 API keys default to short expiry

stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/GlobalConfigService.java, unreleased_changes/20221220_100255_974__3143.md
=> PR for #3143 - NPE updating a property

stroom-search/stroom-search-elastic/src/main/java/stroom/search/elastic/indexing/ElasticIndexingFilter.java
=> Interrupt thread in catch block

stroom-app/src/main/resources/ui/css/components.css, stroom-core-client/src/main/resources/stroom/task/client/view/UserTaskViewImpl.ui.xml, unreleased_changes/20221229_124345_829__3159.md
=> Improve appearance of user task manager

stroom-data/stroom-data-zip/src/main/java/stroom/data/zip/StroomZipFile.java, stroom-data/stroom-data-zip/src/main/java/stroom/data/zip/StroomZipNameSet.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/StroomStreamProcessor.java, unreleased_changes/20230105_131747_964__3166.md
=> PR for #3166 - Export of multiple Streams results in a zip file that cannot be imported to another Stroom instance

stroom-db-util/src/main/java/stroom/db/util/AbstractFlyWayDbModule.java, unreleased_changes/20230109_110239_440__3171.md
=> PR for #3171 - Stroom booting successfully when there are failed DB migrations

stroom-query/stroom-query-api/src/main/java/stroom/datasource/api/v2/IdField.java, unreleased_changes/20230113_091836_815__3180.md
=> Enable `in dictionary` condition for `Id` fields

stroom-core-shared/src/main/java/stroom/processor/shared/TaskStatus.java, stroom-db-util/src/main/java/stroom/db/util/JooqUtil.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorFilterDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorTaskDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorTaskDeleteExecutorImpl.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/AbstractProcessorTest.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/TestProcessorDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/TestProcessorFilterDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/TestProcessorTaskDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/TestProcessorTaskDeleteExecutorImpl.java, stroom-processor/stroom-processor-impl-db/src/test/resources/logback-test.xml, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/MockProcessorDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/MockProcessorFilterDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/MockProcessorTaskDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorConfig.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterDao.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterServiceImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorServiceImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorTaskDao.java, unreleased_changes/20230112_110632_462__3177.md
Fixes #3177 
Supersedes PR #3178
=> Gh 3177 retention job 2

stroom-query/stroom-expression/src/main/java/stroom/dashboard/expression/v1/Distinct.java, stroom-query/stroom-expression/src/test/java/stroom/dashboard/expression/v1/TestDistinct.java, unreleased_changes/20230113_103822_845__1876.md
=> Gh 1876 distinct func

stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorTaskDeleteExecutorImpl.java, unreleased_changes/20230116_124859_241__3189.md
=> PR for #3189 - Ref data effective stream cache performance issues

stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ImportExportSerializerImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterImportExportHandlerImpl.java, unreleased_changes/20230117_183936_288__3192.md
=> PR for #3192 - Dup user events for processor filter export

stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/GlobalConfigService.java, unreleased_changes/20230119_154021_810__3197.md
=> PR for #3197 - Attempting to set stroom.ui.maintenanceMessage results in NPE

stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/text/TextPresenter.java, unreleased_changes/20230119_221400_957__3195.md
=> Fix highlight positions being incorrectly calculated

stroom-processor/stroom-processor-impl-db/src/main/resources/stroom/processor/impl/db/migration/V07_00_18_001__processor_task_idx.sql, unreleased_changes/20230124_093728_891__3204.md
=> PR for #3204 - Deletion of COMPLETED|DELETED processor tasks is very slow

stroom-app/src/test/java/stroom/db/util/TestSlowQueryExecuteListener.java, stroom-app/src/test/resources/logback-test.xml, stroom-db-util/src/main/java/stroom/db/util/JooqUtil.java, stroom-db-util/src/main/java/stroom/db/util/SlowQueryExecuteListener.java, stroom-util/src/main/java/stroom/util/logging/AsciiTable.java, stroom-util/src/test/java/stroom/util/logging/TestAsciiTable.java, unreleased_changes/20230126_154020_471__3209.md
=> PR for #3209 - SQL Slow logging , honestly not an NPE !!!

stroom-core-client/src/main/java/stroom/data/client/presenter/ProcessorTaskListPresenter.java, unreleased_changes/20230131_183943_671__3220.md
=> PR for #3220 - Active Tasks tab doesn't show any detail in the 'i' icon on the lower pane in certain circumstances

stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/AbstractLookup.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestBitmapLookup.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestLookup.java, unreleased_changes/20230211_211503_599__3231.md
=> PR for #3231 - Change missing ref loaders error to warning

stroom-data/stroom-data-store-impl-fs/src/test/java/stroom/data/store/impl/fs/TestFsFileDeleter.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorFilterDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/ProcessorFilterTrackerDaoImpl.java, stroom-processor/stroom-processor-impl-db/src/main/java/stroom/processor/impl/db/RecordToProcessorFilterTrackerMapper.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/TestProcessorFilterDaoImpl.java, stroom-util-shared/src/main/java/stroom/util/shared/PrimitiveValueConverter.java, unreleased_changes/20230215_152317_134__3255.md
=> PR for #3255 - Creating a new Processor Filter gives an error

stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionRulePresenter.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/query/SelectionHandlersPresenter.java
=> Fix incorrect Rest instance type

stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/AbstractRefDataStore.java, unreleased_changes/20230220_153344_236__3272.md
=> PR for #3272 - `Unexpected Processing state Optional[LOAD_IN_PROGRESS]` during ref load

stroom-app/src/test/java/stroom/importexport/TestJsonSerialisation.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/GlobalConfigService.java, stroom-query/stroom-query-api/src/main/java/stroom/datasource/api/v2/AbstractField.java, stroom-util-shared/src/main/java/stroom/util/shared/PropertyPath.java, stroom-util-shared/src/test/java/stroom/util/shared/TestPropertyPath.java, stroom-util/src/main/java/stroom/util/cache/CacheConfig.java, unreleased_changes/20230306_133743_980__3286.md
=> PR for #3286 - Unable to change cache property values

stroom-pipeline/build.gradle, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataResource.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataResourceImpl.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestReferenceDataResourceImpl.java, unreleased_changes/20230307_181835_569__3271.md
=> PR for #3271 - Autologging - ReferenceDataResourceImpl

stroom-data/stroom-data-retention-impl/src/main/java/stroom/data/retention/impl/DataRetentionRulesResourceImpl.java, unreleased_changes/20230308_102550_991__3278.md
=> PR for #3278 - AutoLogging - Remote resource DataRetentionRulesResourceImpl is not configured for autologging.

stroom-event-logging-rs/stroom-event-logging-rs-impl/src/main/java/stroom/event/logging/rs/impl/ContainerResourceInfo.java, stroom-event-logging-rs/stroom-event-logging-rs-impl/src/main/java/stroom/event/logging/rs/impl/RestResourceAutoLoggerImpl.java, stroom-event-logging-rs/stroom-event-logging-rs-impl/src/test/java/stroom/event/logging/rs/impl/TestRestResourceAutoLogger.java, unreleased_changes/20230307_174829_700__3270.md
=> PR for #3270 - STROOM_USER-EVENTS is logging TaskResourceImpl.terminate

stroom-lmdb/src/main/java/stroom/lmdb/serde/UnsignedBytesInstances.java, stroom-lmdb/src/main/java/stroom/lmdb/serde/UnsignedLong.java, stroom-lmdb/src/main/java/stroom/lmdb/serde/UnsignedLongSerde.java, stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeStatusServiceUtil.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/FastInfosetValue.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/NullValue.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/RefDataStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/RefDataValue.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/StringValue.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/UnknownRefDataValue.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/UID.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/databases/EntryStoreDb.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/databases/KeyValueStoreDb.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/databases/RangeStoreDb.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/serdes/ValueStoreMetaSerde.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/onheapstore/OnHeapRefDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/onheapstore/RefDataOnHeapStore.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/TestRefDataOffHeapStore.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/serdes/TestUnsignedLongSerde.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/serdes/TestValueStoreMetaSerde.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/onheapstore/TestRefDataOnHeapStore.java, unreleased_changes/20230309_122957_935__3292.md
=> PR for #3292 - `Can't increment without overflowing` during ref load

stroom-app/src/main/resources/ui/css/ExpanderCell.css, stroom-app/src/main/resources/ui/css/ExpressionItemBox.css, stroom-app/src/main/resources/ui/css/components.css, stroom-app/src/main/resources/ui/css/theme-dark.css, stroom-app/src/main/resources/ui/css/theme-root.css, stroom-core-client-widget/src/main/java/stroom/cell/expander/client/ExpanderCell.java, stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/MenuViewImpl.java, stroom-core-client/src/main/java/stroom/data/client/presenter/MarkerListPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/MetaRelationListPresenter.java, stroom-core-client/src/main/java/stroom/entity/client/presenter/TreeRowHandler.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryResultTablePresenter.java, stroom-core-client/src/main/java/stroom/query/client/view/TimeRangeSelector.java, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionImpactPresenter.java, stroom-core-client/src/main/resources/stroom/query/client/view/QueryButtons.ui.xml, stroom-core-client/src/main/resources/stroom/query/client/view/ResultStoreSettingsViewImpl.ui.xml, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/TablePresenter.java, stroom-dashboard/stroom-dashboard-client/src/main/resources/stroom/dashboard/client/input/BasicListInputSettingsViewImpl.ui.xml, stroom-dashboard/stroom-dashboard-client/src/main/resources/stroom/dashboard/client/main/LayoutConstraintViewImpl.ui.xml
=> Minor UI tweaks (excluding tabs)

stroom-core-client-widget/src/main/java/stroom/cell/info/client/ToolTipCell.java, stroom-core-client/src/main/java/stroom/data/store/impl/fs/client/presenter/FSVolumeEditPresenter.java, stroom-core-client/src/main/java/stroom/data/store/impl/fs/client/presenter/FSVolumeStatusListPresenter.java, stroom-core-client/src/main/java/stroom/index/client/presenter/IndexVolumeEditPresenter.java, stroom-core-client/src/main/java/stroom/index/client/presenter/IndexVolumeStatusListPresenter.java, stroom-util-shared/src/main/java/stroom/util/shared/ModelStringUtil.java, stroom-util/src/test/java/stroom/util/testshared/TestModelStringUtil.java, unreleased_changes/20230314_174020_281__3305.md
=> PR for #3305 - Data Volumes , cannot view value of 19.1T , shows as 19T

stroom-core-client/src/main/java/stroom/cache/client/presenter/CacheNodeListPresenter.java, unreleased_changes/20230413_184638_374__3378.md
=> PR for #3378 - Caches screen creating multiple node columns

stroom-app/src/main/resources/ui/css/celltable/Menu.css, stroom-app/src/main/resources/ui/css/theme-dark.css, stroom-app/src/main/resources/ui/css/theme-dark2.css, stroom-app/src/main/resources/ui/css/theme-root.css, stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/MenuPresenter.java, stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/MenuUiHandlers.java, stroom-core-client-widget/src/main/java/stroom/widget/menu/client/presenter/MenuViewImpl.java, stroom-ui/src/styles/theme-dark.css, stroom-ui/src/styles/theme-dark2.css, stroom-ui/src/styles/theme-root.css, unreleased_changes/20230414_160524_915__3380.md, unreleased_changes/20230414_171145_906__3380.md
=> PR for #3380 - Context menu issues

stroom-cache/stroom-cache-impl/src/main/java/stroom/cache/impl/CacheResourceImpl.java, stroom-cluster/stroom-cluster-lock-impl-db/src/main/java/stroom/cluster/lock/impl/db/ClusterLockResourceImpl.java, stroom-core/src/main/java/stroom/core/entity/event/EntityEventResourceImpl.java, stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeServiceImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/filter/HttpPostFilter.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/ContentSyncService.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/PostDataHelper.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/RemoteNodeSearch.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SessionListListener.java, unreleased_changes/20230512_143219_864__3449.md
=> PR for #3449 - Timeouts waiting to get a http connection

build.gradle, stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnvFactory.java, unreleased_changes/20230530_163523_822__3485.md
=> PR for #3485 - LMDB error on startup beta.19

stroom-app/src/test/java/stroom/dropwizard/common/TestAbstractJerseyClientFactory.java, stroom-config/stroom-config-app/src/main/java/stroom/config/app/Config.java, stroom-dropwizard-common/src/main/java/stroom/dropwizard/common/AbstractJerseyClientFactory.java, stroom-proxy/stroom-proxy-app/proxy-prod.yml.jinja2, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/main/java/stroom/util/config/PropertyUtil.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, stroom-util/src/test/java/stroom/util/config/TestPropertyUtil.java, unreleased_changes/20230530_104540_065__3483.md
=> PR for #3483 - Add sensible defaults for the jersey clients configuration

stroom-app/src/main/resources/ui/css/markdown.css, unreleased_changes/20230615_162843_031__3518.md
=> PR for #3518 - Make rendered Documentation support select & copy

stroom-app/dev.yml, stroom-app/prod.yml.jinja2, stroom-proxy/stroom-proxy-app/proxy-dev.yml, stroom-proxy/stroom-proxy-app/proxy-prod.yml.jinja2, unreleased_changes/20230615_163331_633__3522.md
=> PR for #3522 - Improve client side response for invalid JSON in API calls

stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/EditorPresenter.java, unreleased_changes/20230620_122038_729__3538.md
=> PR for #3538 - NPE when opening expression editor in dash

stroom-core-client-widget/src/main/java/stroom/cell/valuespinner/client/ValueSpinnerCell.java, unreleased_changes/20230620_130518_379__3537.md
=> PR for #3537 - Spinner arrows are broken in beta.32

stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/client/ace/AceEditor.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/EditorPresenter.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/EditorView.java, stroom-core-client-widget/src/main/java/stroom/editor/client/view/Editor.java, stroom-core-client-widget/src/main/java/stroom/editor/client/view/EditorViewImpl.java, stroom-core-client-widget/src/main/java/stroom/widget/popup/client/event/HidePopupEvent.java, stroom-core-client-widget/src/main/java/stroom/widget/popup/client/event/ShowPopupEvent.java, stroom-core-client-widget/src/main/java/stroom/widget/popup/client/view/AbstractPopupPanel.java, stroom-core-client-widget/src/main/java/stroom/widget/util/client/SafeHtmlUtil.java, stroom-core-client/src/test/java/stroom/util/client/TestSafeHtmlUtil.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/ExpressionPresenter.java, unreleased_changes/20230621_094128_598__3541.md
=> PR for #3541 - `esc` to close dialogs is not compatible with vim key bindings

stroom-core-client/src/main/java/stroom/pipeline/stepping/client/presenter/SteppingPresenter.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PipelineStructurePresenter.java, unreleased_changes/20230621_162402_561__3544.md
=> PR for #3544 - Stepping filter icon doesn't clear if at end of Stream

stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, unreleased_changes/20230621_163055_633__3487.md
=> PR for #3487 - Unnecessary WARN when RefStreamDefinition is already loaded

stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/DashboardResourceImpl.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/DashboardServiceImpl.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/logging/SearchEventLog.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/logging/SearchEventLogImpl.java, stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/ExpressionUtil.java, stroom-query/stroom-query-api/src/test/java/stroom/query/api/v2/TestExpressionUtil.java, unreleased_changes/20230707_123517_974__3588.md
=> PR for #3588 - Stroom Logging: Parameter values from the DS Bar are missing

stroom-core-client/src/main/java/stroom/query/client/presenter/FunctionSignatureUtil.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryHelpItem.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryHelpPresenter.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryStructure.java, unreleased_changes/20230710_094032_890__3566.md
=> PR for #3566 - Query Picker Help - click highlight issue

stroom-app/prod.yml.jinja2, stroom-proxy/stroom-proxy-app/proxy-prod.yml.jinja2, unreleased_changes/20230711_144436_643__3580.md
=> PR for #3580 - Log rolling - dropping events

stroom-app/src/test/java/stroom/pipeline/factory/MockPipelineElementRegistryFactory.java, stroom-app/src/test/resources/logback-test.xml, stroom-docref/src/main/java/stroom/docref/DocRef.java, stroom-explorer/stroom-docrefinfo-api/src/main/java/stroom/docrefinfo/api/DocRefInfoService.java, stroom-explorer/stroom-docrefinfo-mock/src/main/java/stroom/docrefinfo/mock/MockDocRefInfoModule.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/DocRefInfoCache.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/DocRefInfoModule.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/DocRefInfoServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerModule.java, stroom-explorer/stroom-explorer-impl/src/test/java/stroom/explorer/impl/TestDocRefInfoServiceImpl.java, stroom-headless/src/main/java/stroom/headless/CliModule.java, stroom-pipeline/src/main/java/stroom/pipeline/errorhandler/ErrorReceiverProxy.java, stroom-pipeline/src/main/java/stroom/pipeline/errorhandler/LoggingErrorReceiver.java, stroom-pipeline/src/main/java/stroom/pipeline/filter/DocFinder.java, stroom-pipeline/src/main/java/stroom/pipeline/filter/XsltFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/parser/CombinedParser.java, stroom-pipeline/src/main/java/stroom/pipeline/parser/DSParser.java, stroom-pipeline/src/main/java/stroom/pipeline/parser/XMLFragmentParser.java, stroom-pipeline/src/main/java/stroom/pipeline/stepping/SteppingController.java, stroom-pipeline/src/main/java/stroom/pipeline/stepping/SteppingRequestHandler.java, stroom-pipeline/src/main/java/stroom/pipeline/stepping/SteppingResourceImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/stepping/SteppingService.java, stroom-pipeline/src/main/java/stroom/pipeline/writer/XMLWriter.java, stroom-pipeline/src/test/java/stroom/pipeline/xml/converter/json/TestJSONParser.java, unreleased_changes/20230712_122611_052__3570.md, unreleased_changes/20230712_144138_093__290.md
=> PR for #3570 - XSLTFilter namePattern failures can show wrong name in error message

stroom-core-shared/src/main/java/stroom/query/shared/QuerySearchRequest.java, stroom-processor/stroom-processor-impl-db/src/test/java/stroom/processor/impl/db/TestProcessorFilterMarshaller.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorTaskQueueManagerImpl.java, stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/Param.java, stroom-query/stroom-query-api/src/test/resources/searchRequestPortrait-current.txt, stroom-query/stroom-query-api/src/test/resources/searchRequestPortrait-new.txt, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/QueryServiceImpl.java, unreleased_changes/20230714_143317_578__3607.md
=> PR for #3607 - NPE in `ProcessorTaskQueueManagerImpl#fillTaskQueueAsync`

stroom-core-client/src/main/java/stroom/query/client/presenter/FunctionSignatureUtil.java, unreleased_changes/20230725_162246_990__3623.md
=> PR for #3623 - Code completion missing brackets for no args functions

stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/LmdbDataStore.java, stroom-query/stroom-query-common/src/test/java/stroom/query/common/v2/AbstractDataStoreTest.java, stroom-query/stroom-query-common/src/test/java/stroom/query/common/v2/TestLmdbDataStore.java, stroom-query/stroom-query-common/src/test/java/stroom/query/common/v2/TestMapDataStore.java, unreleased_changes/20230725_160800_062__3622.md
=> PR for #3622 - `Dual` data source doesn't return row if `Dummy` field is not a column

stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/DelegatingRefDataOffHeapStore.java, unreleased_changes/20230731_152857_221__3635.md
=> PR for #3635 - Ref data store initialisation not handling unknown feeds properly

stroom-proxy/stroom-proxy-app/proxy-prod.yml.jinja2, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/ProxyConfig.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/forwarder/ForwardFileConfig.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/dist/GenerateProxyExpectedYaml.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/dist/TestProxyYamlUtil.java, stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml, stroom-util/src/main/java/stroom/util/config/PropertyUtil.java, unreleased_changes/20230801_092358_225__3638.md
=> PR for #3638 - Update vanilla proxy config for forward destinations

stroom-app/src/main/resources/ui/css/components.css, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/ConfigProvidersModule.java, stroom-core-client/src/main/java/stroom/node/client/presenter/NodeMonitoringPresenter.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/NodeMonitoringConfig.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/UiConfig.java, stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeResourceImpl.java, unreleased_changes/20230801_141659_743__3649.md
=> PR for #3649 - Change node ping bars to have consistent scale

stroom-core-client/src/main/java/stroom/query/client/presenter/QueryStructure.java, unreleased_changes/20230802_154741_834__3631.md
=> PR for #3631 - StroomQL Query Helper - Structure is not being populated

stroom-core-client/src/main/java/stroom/data/client/presenter/SourcePresenter.java, stroom-core-client/src/main/java/stroom/data/client/view/SourceViewImpl.java, stroom-core-client/src/main/resources/stroom/data/client/view/SourceViewImpl.ui.xml, unreleased_changes/20230802_180053_575__3659.md
=> PR for #3659 - Source screen is showing a record number for raw data

stroom-app/src/main/resources/ui/css/components.css, stroom-core-client/src/main/resources/stroom/data/client/view/DataViewImpl.ui.xml, stroom-core-client/src/main/resources/stroom/processor/client/view/ProcessorViewImpl.ui.xml, unreleased_changes/20230802_174050_200__3667.md
=> PR for #3667 - Stream Browser bottom pane not scrollable

stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerConstants.java, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerNode.java, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerNodeKey.java, stroom-explorer/stroom-explorer-impl-db/src/main/java/stroom/explorer/impl/db/ExplorerTreeDaoImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerNodeServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, unreleased_changes/20230803_175849_340__3618.md
=> PR for #3618 - Cannot select Dual as a Data Source. 

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryHelpPresenter.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/UiConfig.java, unreleased_changes/20230824_081800_818__3704.md
=> PR for #3704 - Make delimiter for nested index fields configurable

stroom-node/stroom-node-impl/src/main/java/stroom/node/impl/NodeStatusServiceUtil.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/ValueStore.java, unreleased_changes/20230824_154314_309__3679.md
=> PR for #3679 - Reference Data Statistics are missing Feed

stroom-core-client/src/main/java/stroom/query/client/presenter/QueryEditPresenter.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryHelpPresenter.java, stroom-dashboard/stroom-dashboard-client/src/main/java/stroom/dashboard/client/table/ColumnFunctionEditorPresenter.java, unreleased_changes/20230829_110236_301__3709.md
=> PR for #3709 - StroomQL Query Helper - only showing Data Sources that have Documentation

stroom-app/src/main/resources/ui/css/editor.css, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/client/ace/AceCompletionLazySnippet.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/DelegatingAceCompleter.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/KeyedAceCompletionProvider.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/LazyCompletion.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryEditPresenter.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryHelpItem.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryHelpPresenter.java, stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/StructureElementServiceImpl.java, unreleased_changes/20230905_124457_708__3724.md, unreleased_changes/20230905_124529_101__0.md, unreleased_changes/20230905_124610_288__0.md, unreleased_changes/20230905_124846_309__0.md, unreleased_changes/20230905_153924_980__3714.md
=> PR for #3724 - DataSource names missing from autocomplete in Qury Helper

.idea/runConfigurations/Stroom_Create_Admin_Identity_Account.xml, .idea/runConfigurations/Stroom_Create_Admin_Permissions.xml, .idea/runConfigurations/Stroom_Grant_admin_to_IDP_user.xml, stroom-app/src/main/java/stroom/app/commands/ManageUsersCommand.java, stroom-core-shared/src/main/java/stroom/security/shared/User.java, stroom-event-logging/stroom-event-logging-api/src/main/java/stroom/event/logging/api/StroomEventLoggingUtil.java, stroom-util-shared/src/main/java/stroom/util/shared/UserName.java, unreleased_changes/20230906_145055_909__3729.md, unreleased_changes/20230906_145143_227__0.md
=> PR for #3729 - Stroom logging generating non-schema compliant logs

stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerDropDownTreePresenter.java, unreleased_changes/20230911_152146_161__3738.md
=> PR for #3738 - Stream Browser Error

stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/TableBuilderAnalyticExecutor.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/CurrentDbStateFactory.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/LmdbDataStore.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/BasicUserIdentity.java, stroom-test-common/src/main/java/stroom/test/common/DynamicTestBuilder.java, stroom-util/src/main/java/stroom/util/time/SimpleDurationUtil.java, unreleased_changes/20230920_092623_738__3757.md
=> PR for #3757 - Internal IDP Rule errors

stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/DetectionConsumerProxy.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/ScheduledQueryAnalyticExecutor.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/StreamingAnalyticExecutor.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/TableBuilderAnalyticExecutor.java, stroom-core-shared/src/main/java/stroom/processor/shared/ProcessorFilter.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorFilterServiceImpl.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorTaskCreatorImpl.java, stroom-query/stroom-expression/src/main/java/stroom/dashboard/expression/v1/FieldIndex.java, stroom-security/stroom-security-api/build.gradle, stroom-security/stroom-security-api/src/main/java/stroom/security/api/SecurityContext.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocumentOwnerPermissionsCache.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityContextImpl.java, stroom-security/stroom-security-impl/src/test/java/stroom/security/impl/TestSecurityContextImpl.java, stroom-security/stroom-security-mock/build.gradle, stroom-security/stroom-security-mock/src/main/java/stroom/security/mock/MockSecurityContext.java, stroom-test-common/src/main/java/stroom/test/common/TestUtil.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/main/java/stroom/util/logging/LogUtil.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, stroom-util/src/test/java/stroom/util/logging/TestLogUtil.java, unreleased_changes/20230920_155608_836__3756.md
=> PR for #3756 - Rule Owner

stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/ServiceUserIdentity.java, unreleased_changes/20230925_114014_916__3773.md
=> PR for #3773 - Processing User display on OIDC instance

stroom-dashboard/stroom-dashboard-impl/src/main/java/stroom/dashboard/impl/DashboardServiceImpl.java, stroom-query/stroom-expression-api/src/main/java/stroom/expression/api/DateTimeSettings.java, stroom-query/stroom-expression-api/src/main/java/stroom/expression/api/ExpressionContext.java, stroom-query/stroom-expression/src/main/java/stroom/dashboard/expression/v1/AbstractTimeFunction.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/ExpressionContextFactory.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/ResultStoreManager.java, unreleased_changes/20230925_150433_676__3776.md
=> PR for #3776 - referenceTime is a fixed date set at download Time

stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, unreleased_changes/20231002_191150_392__3798.md
=> PR for #3798 - Tags context item is too near Delete 

stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerTreeModel.java, unreleased_changes/20231003_081743_276__3805.md
=> PR for #3805 - b.69 UI NPE on startup

stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/NodeInclusionChecker.java, unreleased_changes/20231003_082708_120__3801.md
=> PR for #3801 - Quick Filter NPE

stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerDropDownTreePresenter.java, unreleased_changes/20231003_112220_794__3800.md
=> PR for #3800 - Rules->Feed for Error is not persisting/displaying my choice

stroom-core-client/src/main/java/stroom/documentation/client/presenter/DocumentationPresenter.java, stroom-core-shared/src/main/java/stroom/documentation/shared/DocumentationDoc.java, stroom-documentation/stroom-documentation-impl/src/main/java/stroom/documentation/impl/DocumentationSerialiser.java, unreleased_changes/20231003_140001_840__3796.md
=> PR for #3796 - Documentation Objects appear twice in Find Content results

stroom-app/src/main/resources/ui/css/components.css, stroom-core-client/src/main/java/stroom/pipeline/stepping/client/presenter/SteppingFilterPresenter.java, unreleased_changes/20231003_145834_620__3770.md
=> PR for #3770 - Change Step Filters , Filter icon not fully visible, scrollbar

stroom-app/src/main/java/stroom/app/commands/ManageUsersCommand.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserAppPermissionServiceImpl.java, unreleased_changes/20231003_171246_933__3771.md
=> PR for #3771 - CliAddToGroup is producing invalid Event Logging XML

stroom-core-client/src/main/java/stroom/alert/client/event/AlertEvent.java, stroom-core-client/src/main/java/stroom/alert/client/view/CommonAlertViewImpl.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaStatusId.java, unreleased_changes/20231004_105657_832__3745.md, unreleased_changes/20231004_105735_192__0.md
=> PR for #3745 - Stream browser nasty looking error message

stroom-app/src/main/resources/ui/css/components.css, stroom-app/src/main/resources/ui/css/icon-colours.css, stroom-app/src/main/resources/ui/css/stroom-button.css, stroom-app/src/main/resources/ui/css/theme-dark.css, stroom-app/src/main/resources/ui/css/theme-root.css, stroom-core-client/src/main/java/stroom/dashboard/client/text/TextViewImpl.java, stroom-core-client/src/main/java/stroom/main/client/presenter/MainPresenter.java, stroom-core-client/src/main/resources/stroom/explorer/client/view/NavigationViewImpl.ui.xml, stroom-core-shared/src/main/java/stroom/ui/config/shared/ThemeConfig.java, unreleased_changes/20231004_095535_929__3810.md, unreleased_changes/20231004_095843_880__0.md
=> PR for #3810 - Light Mode, can it look more like 7.0

stroom-app/src/main/resources/ui/css/components.css, stroom-core-client/src/main/java/stroom/document/client/event/CreateDocumentEvent.java, stroom-core-shared/src/main/java/stroom/explorer/shared/DocumentTypes.java, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerConstants.java, stroom-core-shared/src/main/java/stroom/security/shared/Changes.java, stroom-core-shared/src/main/java/stroom/security/shared/DocumentPermissionNames.java, stroom-core-shared/src/main/java/stroom/security/shared/DocumentPermissions.java, stroom-core-shared/src/main/java/stroom/security/shared/PermissionNames.java, stroom-core-shared/src/main/java/stroom/security/shared/User.java, stroom-core-shared/src/main/java/stroom/security/shared/UserNameProvider.java, stroom-core-shared/src/main/java/stroom/security/shared/UserNameResource.java, stroom-core-shared/src/test/java/stroom/security/shared/TestDocumentPermissions.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerNodeServiceImpl.java, stroom-feed/stroom-feed-impl/src/test/java/stroom/feed/impl/TestMetaSecurityFilterImpl.java, stroom-security/stroom-security-api/src/main/java/stroom/security/api/DocumentPermissionService.java, stroom-security/stroom-security-api/src/main/java/stroom/security/api/SecurityContext.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/DocumentPermissionsPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/DocumentPermissionsTabPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/PermissionsListPresenter.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/UserNameDataProvider.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/account/AccountServiceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocumentPermissionServiceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/StroomUserNameProvider.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserNameResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserNameServiceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserServiceImpl.java, stroom-security/stroom-security-impl/src/test/java/stroom/security/impl/TestUserNameServiceImpl.java, stroom-security/stroom-security-user-api/src/main/java/stroom/security/user/api/UserNameService.java, unreleased_changes/20231006_083837_323__3797.md
=> PR for #3797 - Folder Permission Error Adding Users

stroom-app/src/main/java/stroom/app/BootstrapUtil.java, unreleased_changes/20231006_151238_609__3822.md
=> PR for #3822 - NPE during bootstrap process

stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/NewElementPresenter.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PipelineStructurePresenter.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PipelineTreePresenter.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProgressMonitor.java, unreleased_changes/20231009_100931_650__3827.md
=> PR for #3827 - New pipeline element dialog suggesting duplicate names

stroom-app/docker/Dockerfile, stroom-app/src/main/resources/ui/noauth/swagger/stroom.json, stroom-app/src/main/resources/ui/noauth/swagger/stroom.yaml, stroom-proxy/stroom-proxy-app/docker/Dockerfile, stroom-proxy/stroom-proxy-app/docker/docker-entrypoint.sh, stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml, stroom-proxy/stroom-proxy-repo/src/main/java/stroom/proxy/repo/ProxyDbConfig.java, stroom-proxy/stroom-proxy-repo/src/main/java/stroom/proxy/repo/ProxyDbModule.java, stroom-proxy/stroom-proxy-repo/src/test/java/stroom/proxy/repo/ProxyRepoTestModule.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/AuthenticationService.java, stroom-test-common/src/main/java/stroom/test/common/util/test/TestingHomeAndTempProvidersModule.java, stroom-ui/src/api/stroom.ts
=> PR for #3026 - Proxy does not have a docker managed vol for the sqlite DB

stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/databases/ValueStoreMetaDb.java, unreleased_changes/20231011_101703_838__3838.md
=> PR for #3838 - Ref data purge failing due to missing value store meta entries

stroom-app/src/main/resources/ui/noauth/swagger/stroom.json, stroom-app/src/main/resources/ui/noauth/swagger/stroom.yaml, stroom-core-client/src/main/java/stroom/config/global/client/presenter/ManageGlobalPropertyEditPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, stroom-core-client/src/main/java/stroom/data/store/impl/fs/client/presenter/ManageFSVolumesPresenter.java, stroom-core-client/src/main/java/stroom/dispatch/client/RestFactory.java, stroom-core-client/src/main/java/stroom/dispatch/client/RestFactoryImpl.java, stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/FindPresenter.java, stroom-statistics/stroom-statistics-client/src/main/java/stroom/statistics/impl/hbase/client/presenter/StroomStatsStoreCustomMaskListPresenter.java, stroom-ui/src/api/stroom.ts
- Refactor RestFactory for easier type management
- Add forBoolean method, fix empty diamonds for GWT
=> refactor rest factory

stroom-core-client/src/main/resources/stroom/dashboard/client/query/QueryInfoViewImpl.ui.xml, unreleased_changes/20231016_143310_482__3845.md
=> PR for #3845 - Comedy Small Additional Info box when Provide Additional Query Context box is selected

stroom-core-client-widget/src/main/java/stroom/data/grid/client/DataGridSelectionEventManager.java, unreleased_changes/20231024_111010_631__3864.md, unreleased_changes/20231024_111059_264__0.md
=> PR for #3864 - Right clicking table rows in Query does multi-select

stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/EditorPresenter.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/EditorView.java, stroom-core-client-widget/src/main/java/stroom/editor/client/view/EditorViewImpl.java, stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/TextPresenter.java, unreleased_changes/20231024_151830_977__3857.md
=> PR for #3857 - Unable to Display Bad Data as Hex

stroom-app/src/main/resources/ui/css/components.css, stroom-core-client-widget/src/main/java/stroom/widget/tooltip/client/presenter/TooltipPresenter.java, stroom-core-client-widget/src/main/java/stroom/widget/util/client/TableCell.java, stroom-core-client/src/main/java/stroom/task/client/presenter/TaskManagerListPresenter.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobSystemModule.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoadTaskHandler.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/RefDataOffHeapStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/StoreMigrator.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorModule.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskContextFactoryImpl.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskManagerImpl.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskModule.java, unreleased_changes/20231025_142844_415__0.md, unreleased_changes/20231025_142916_776__0.md, unreleased_changes/20231025_143008_122__3868.md
=> PR for #3868 - Improve task logging for ref purges, load and migrations

stroom-app-gwt/src/main/java/stroom/app/client/gin/AppGinjectorUser.java, stroom-app-gwt/src/main/java/stroom/app/client/gin/AppModule.java, stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, stroom-core-client/src/main/java/stroom/document/client/event/RefreshDocumentEvent.java, stroom-core-client/src/main/java/stroom/explorer/client/event/ShowEditNodeTagsDialogEvent.java, stroom-core-client/src/main/java/stroom/explorer/client/event/ShowExplorerNodeTagsDialogEvent.java, stroom-core-client/src/main/java/stroom/explorer/client/event/ShowRemoveNodeTagsDialogEvent.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerNodeEditTagsPresenter.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerNodeRemoveTagsPresenter.java, stroom-core-client/src/main/java/stroom/explorer/client/view/ExplorerNodeEditTagsViewImpl.java, stroom-core-client/src/main/java/stroom/explorer/client/view/ExplorerNodeRemoveTagsViewImpl.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryResultTablePresenter.java, stroom-core-client/src/main/resources/stroom/explorer/client/view/ExplorerNodeEditTagsViewImpl.ui.xml, stroom-core-client/src/main/resources/stroom/explorer/client/view/ExplorerNodeRemoveTagsViewImpl.ui.xml, stroom-core-shared/src/main/java/stroom/explorer/shared/AddRemoveTagsRequest.java, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerResource.java, stroom-explorer/stroom-explorer-api/src/main/java/stroom/explorer/api/ExplorerService.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerResourceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/MockExplorerService.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/UnmodifiableTreeModel.java, unreleased_changes/20231026_143403_368__3814.md
=> PR for #3814 - I'd like to be able to add/remove Tags from multiple Objects

stroom-app/src/main/java/stroom/app/App.java, stroom-app/src/main/java/stroom/app/commands/AbstractStroomAccountConfiguredCommand.java, stroom-app/src/main/java/stroom/app/commands/AbstractStroomAppCommand.java, stroom-app/src/main/java/stroom/app/commands/AbstractStroomBaseCommand.java, stroom-app/src/main/java/stroom/app/commands/CreateAccountCommand.java, stroom-app/src/main/java/stroom/app/commands/CreateApiKeyCommand.java, stroom-app/src/main/java/stroom/app/commands/DbMigrationCommand.java, stroom-app/src/main/java/stroom/app/commands/FetchAccessTokenCommand.java, stroom-app/src/main/java/stroom/app/commands/ManageUsersCommand.java, stroom-app/src/main/java/stroom/app/commands/ResetPasswordCommand.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/ServiceUserIdentity.java, stroom-util/src/main/java/stroom/util/exception/LambdaExceptionUtil.java, stroom-util/src/main/java/stroom/util/logging/LogUtil.java, stroom-util/src/test/java/stroom/util/logging/TestLogUtil.java, unreleased_changes/20231124_175108_662__3926.md
=> PR for #3926 - Create CLI command to fetch external IDP token using client creds flow

stroom-core-client/src/main/java/stroom/data/client/presenter/DataPresenter.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsSource.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/AttributeMap.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/AttributeMapUtil.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/CIStringHashMap.java, stroom-meta/stroom-meta-api/src/test/java/stroom/meta/api/TestAttributeMap.java, stroom-meta/stroom-meta-api/src/test/java/stroom/meta/api/TestAttributeMapUtil.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/StreamTargetStreamHandler.java, unreleased_changes/20231117_131420_531__3915.md
=> PR for #3915 - `Files` attribute in manifest file has `\n` in its values

stroom-data/stroom-data-zip/build.gradle, stroom-data/stroom-data-zip/src/main/java/stroom/data/zip/StroomZipEntries.java, stroom-data/stroom-data-zip/src/main/java/stroom/data/zip/StroomZipEntry.java, stroom-data/stroom-data-zip/src/main/java/stroom/data/zip/StroomZipFileType.java, stroom-data/stroom-data-zip/src/test/java/stroom/data/zip/TestStroomZipEntries.java, stroom-data/stroom-data-zip/src/test/java/stroom/data/zip/TestStroomZipEntry.java, stroom-data/stroom-data-zip/src/test/java/stroom/data/zip/TestStroomZipFileType.java, stroom-proxy/stroom-proxy-repo/src/test/java/stroom/proxy/repo/TestStroomStreamProcessor.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/StroomStreamProcessor.java, stroom-test-common/src/main/java/stroom/test/common/DynamicTestBuilder.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/main/java/stroom/util/io/FileName.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20231115_155802_415__3913.md
=> PR for #3913 - `Duplicate File xxxxx` exception incorrectly thrown for received zips

stroom-event-logging/stroom-event-logging-api/src/main/java/stroom/event/logging/api/StroomEventLoggingUtil.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/AppPermissionResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/AuthorisationEventLog.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityModule.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserObjectInfoProvider.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserResourceImpl.java, unreleased_changes/20231211_151023_787__3942.md
=> PR for #3942 - Stroom Logging for Create User with external IDP

stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/IPInCidr.java, unreleased_changes/20240102_042807_153__3964.md
=> Add `ip-in-cidr` XSLT method

stroom-app/src/test/java/stroom/pipeline/refdata/TestReferenceData.java, stroom-lmdb/src/main/java/stroom/bytebuffer/ByteBufferPoolImpl4.java, stroom-lmdb/src/main/java/stroom/lmdb/LmdbEnv.java, stroom-pipeline/src/main/java/stroom/pipeline/errorhandler/ProcessException.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceData.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataFilter.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataLoadTaskHandler.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/AbstractRefDataStore.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/ProcessingState.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/OffHeapRefDataLoader.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/AbstractLookup.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/BitmapLookup.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/Lookup.java, stroom-pipeline/src/test/java/stroom/pipeline/errorhandler/TestProcessException.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestAbstractLookup.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestBitmapLookup.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestLookup.java, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/ExtractionDecorator.java, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/ExtractionTaskHandler.java, stroom-task/stroom-task-api/src/main/java/stroom/task/api/TaskTerminatedException.java, stroom-util/src/main/java/stroom/util/concurrent/UncheckedInterruptedException.java, unreleased_changes/20231222_144605_067__3952.md
=> PR for #3952 - Error Loading Ref Data

stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerTreeModel.java, unreleased_changes/20240116_145700_597__3990.md
=> PR for #3990 - Explorer tree update problem

stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, unreleased_changes/20240116_185551_208__4012.md
=> PR for #4012 - NPE when adding cascade perms to a folder with no perms

stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/AnalyticDataStores.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/AnalyticRuleSearchRequestHelper.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/AnalyticUtil.java, stroom-query/stroom-query-common/src/main/java/stroom/query/language/SearchRequestFactory.java, unreleased_changes/20240117_114640_230__4010.md
=> PR for #4010 - Empty analytic rules causing errors

stroom-query/stroom-query-language/src/main/java/stroom/query/language/functions/ValSerialiser.java, stroom-query/stroom-query-language/src/test/java/stroom/query/language/functions/TestValSerialiser.java, stroom-test-common/src/main/java/stroom/test/common/DynamicTestBuilder.java, unreleased_changes/20240118_150633_006__4021.md
=> PR for #4021 - max() on a parseDuration() gives FATAL

stroom-explorer/stroom-docrefinfo-api/src/main/java/stroom/docrefinfo/api/DocRefInfoService.java, stroom-explorer/stroom-docrefinfo-mock/src/main/java/stroom/docrefinfo/mock/MockDocRefInfoService.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/DocRefInfoServiceImpl.java, stroom-importexport/stroom-importexport-api/src/main/java/stroom/importexport/api/ImportExportActionHandler.java, stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/CoprocessorsFactory.java, stroom-query/stroom-query-common/src/main/java/stroom/query/language/DocResolver.java, stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/LuceneSearchProvider.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, stroom-view/stroom-view-impl/src/main/java/stroom/view/impl/ViewSearchProvider.java, unreleased_changes/20240118_125848_462__4007.md
=> PR for #4007 - Query an Index, only `Stored` fields can be `Select`ed

stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CidrToNumericIPRange.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/IPInCidr.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/MetaKeys.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/NumericIP.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/AbstractXsltFunctionTest.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestCidrToNumericIPRange.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestIPinCidr.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestNumericIP.java, stroom-util/src/main/java/stroom/util/net/IpAddressUtil.java, unreleased_changes/20240108_124934_990__3975.md
=> Add `cidr-to-numeric-ip-range` XSLT function

stroom-app/src/test/java/stroom/dropwizard/common/TestRestResources.java, stroom-core-shared/src/main/java/stroom/dashboard/shared/DashboardResource.java, stroom-core-shared/src/main/java/stroom/query/shared/QueryResource.java, unreleased_changes/20240122_131315_378__4029.md
=> PR for #4029 - `/api/query/v1/search` is not available

stroom-index/stroom-index-impl-db/build.gradle, stroom-index/stroom-index-impl-db/src/main/java/stroom/index/impl/db/IndexShardDaoImpl.java, unreleased_changes/20240123_155128_048__3900.md
=> PR for #3900 - Dashboard Query of Index Shards Datasource errors on `Last Commit`

stroom-app/src/test/java/stroom/search/TestQueuesWithTaskContext.java, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/ExtractionDecorator.java, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/StreamEventMap.java, stroom-search/stroom-search-extraction/src/test/java/stroom/search/extraction/TestStreamEventMap.java, stroom-search/stroom-search-impl/src/test/java/stroom/search/impl/TestQueues.java, stroom-util/src/main/java/stroom/util/concurrent/CompletableQueue.java, stroom-util/src/test/java/stroom/util/concurrent/TestCompletableQueue.java, unreleased_changes/20240123_102637_872__4024.md
=> PR for #4024 - Stuck Search Tasks v7.2.20 (LMDB?)

stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/HexToString.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestHexToString.java, unreleased_changes/20240204_051504_994__4082.md
=> Add XSLT function `hex-to-string`

stroom-lmdb/src/main/java/stroom/lmdb/serde/UnsignedBytesInstances.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/ValueStoreMeta.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/databases/ValueStoreMetaDb.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/offheapstore/serdes/ValueStoreMetaSerde.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/TestUnsignedBytesInstancesThree.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/offheapstore/databases/TestValueStoreMetaDb.java, unreleased_changes/20240205_131110_568__4085.md
=> PR for #4085 - Ref data: can't increment without overflowing

stroom-core-client/src/main/java/stroom/data/client/presenter/AbstractMetaListPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/MetaPresenter.java, unreleased_changes/20240212_134326_137__4097.md
=> PR for #4097 - 7.3 Filter Steam expression (metadata) terms not working

stroom-core-client/src/main/java/stroom/query/client/DataSourceClient.java
=> Fix incorrect expression field being selected on drop-down

stroom-app/src/test/java/stroom/app/docs/GenerateSnippetsDoc.java, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/client/ace/AceEditorMode.java, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/README.md, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/mode-stroom_combined_parser.js, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/mode-stroom_data_splitter.js, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/mode-stroom_fragment_parser.js, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/mode-xml.js, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/snippets/stroom_combined_parser.js, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/snippets/stroom_data_splitter.js, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/snippets/stroom_fragment_parser.js, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/public/ace/snippets/xml.js, stroom-core-client/src/main/java/stroom/pipeline/client/presenter/TextConverterPresenter.java, stroom-core-client/src/main/java/stroom/pipeline/stepping/client/presenter/ElementPresenter.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/TextConverterDoc.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/data/PipelineElementType.java, stroom-core/src/main/resources/stroom/core/servlet/app.html, stroom-pipeline/src/main/java/stroom/pipeline/parser/CombinedParser.java, stroom-pipeline/src/main/java/stroom/pipeline/parser/DSParser.java, stroom-pipeline/src/main/java/stroom/pipeline/parser/XMLFragmentParser.java, stroom-pipeline/src/main/java/stroom/pipeline/xml/converter/xmlfragment/XMLFragmentParser.java, stroom-query/stroom-query-language/src/main/java/stroom/query/language/functions/PatternCache.java, unreleased_changes/20240222_161533_649__4108.md
=> PR for #4108 - Snippets for Parser

stroom-app/src/main/java/stroom/app/commands/CreateApiKeyCommand.java, stroom-core-client/src/main/java/stroom/processor/client/presenter/ProcessorStatusUtil.java, stroom-security/stroom-security-client/src/main/java/stroom/security/client/presenter/EditApiKeyPresenter.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/apikey/ApiKeyService.java, stroom-security/stroom-security-impl/src/test/java/stroom/security/impl/apikey/TestApiKeyService.java, unreleased_changes/20240223_164736_050__4117.md
=> PR for #4117 - Inconsistencies between api keys screen and cli command

stroom-core-shared/src/main/java/stroom/explorer/shared/FindResult.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, unreleased_changes/20240223_105557_989__4115.md
=> PR for #4115 - Recent items screen erroring if a recent item is in Favourites

build.gradle
=> PR for #4133 - LMDB errors 7.3

stroom-core-client/src/main/java/stroom/data/client/presenter/CopyTextUtil.java, stroom-core-client/src/main/java/stroom/data/client/presenter/DocRefCell.java, stroom-util-shared/src/main/java/stroom/util/shared/GwtNullSafe.java, stroom-util-shared/src/test/java/stroom/util/shared/TestGwtNullSafe.java, unreleased_changes/20240229_130839_180__4132.md
=> PR for #4132 - Tooltip for new Open/Copy options in stream browser please

stroom-core-shared/src/main/java/stroom/index/shared/LuceneIndexField.java, unreleased_changes/20240320_121301_971__4169.md
=> PR for #4169 - 7.3 Corrupting Index Shards 

stroom-core-client/src/main/java/stroom/dashboard/client/main/SearchModel.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryEditPresenter.java, unreleased_changes/20240320_125211_242__4172.md
=> PR for #4172 - NPE when running an empty sQL Query

stroom-core-client-widget/src/main/java/stroom/widget/popup/client/event/ShowPopupEvent.java, stroom-core-client/src/main/java/stroom/entity/client/presenter/InfoDocumentPresenter.java, unreleased_changes/20240409_130752_775__4178.md
=> PR for #4178 - Info Popup

stroom-app/src/test/java/stroom/db/migration/TestListDbMigrations.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/DocRefInfoCache.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerActionHandlers.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/FolderExplorerActionHandler.java, stroom-explorer/stroom-explorer-impl/src/test/java/stroom/explorer/impl/TestDocRefInfoCache.java, stroom-util/src/main/java/stroom/util/AbstractCommandLineTool.java, unreleased_changes/20240409_121525_658__4192.md
=> PR for #4192 - NPE when selecting Info in the explorer context menu for a Folder

stroom-lmdb/src/main/java/stroom/bytebuffer/ByteBufferPoolImpl4.java, unreleased_changes/20240410_111120_568__4196.md
=> PR for #4196 - ByteBufferPoolImpl message is incorrect

build.gradle, stroom-analytics/stroom-analytics-impl/build.gradle, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/AnalyticsConfig.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/SmtpConfig.java, stroom-analytics/stroom-analytics-impl/src/test/java/stroom/analytics/impl/TestEmailSender.java, stroom-security/stroom-security-identity/build.gradle, unreleased_changes/20240410_130458_422__4175.md
=> PR for #4175 - Error in EmailSender

stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/internal/SQLInternalStatisticsService.java, unreleased_changes/20240410_144848_564__4199.md
=> PR for #4199 - Proc Filters owned by Low Priv Users failing to update PipelineStreamProcerssor SQL Stat store

stroom-core-shared/src/main/java/stroom/index/shared/IndexFieldImpl.java, stroom-core-shared/src/main/java/stroom/index/shared/LuceneIndexField.java, stroom-index/stroom-index-impl-db/src/main/java/stroom/index/impl/db/IndexFieldDaoImpl.java, stroom-index/stroom-index-impl-db/src/test/java/stroom/index/impl/db/TestIndexFieldDaoImpl.java, unreleased_changes/20240410_200322_113__4195.md
=> PR for #4195 - SQL Deadlock 7.3

stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceData.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/store/onheapstore/RefDataOnHeapStore.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/store/onheapstore/TestRefDataOnHeapStore.java, unreleased_changes/20240416_142821_562__4215.md
=> PR for #4215 - ERROR during lookup()

stroom-core-shared/src/main/java/stroom/index/shared/IndexShard.java, stroom-index/stroom-index-impl-db/src/main/java/stroom/index/impl/db/IndexShardDaoImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/ActiveShardsCacheImpl.java, unreleased_changes/20240429_155759_127__4240.md
=> PR for #4240 - Stroom creating too many shards per partition

stroom-core-client/src/main/java/stroom/query/client/presenter/QueryHelpAceCompletionProvider.java, stroom-core-shared/src/main/java/stroom/query/shared/CompletionItem.java, stroom-core-shared/src/main/java/stroom/query/shared/CompletionSnippet.java, stroom-core-shared/src/main/java/stroom/query/shared/InsertType.java, stroom-core-shared/src/main/java/stroom/query/shared/QueryResource.java, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/DataSources.java, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/Fields.java, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/Functions.java, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/QueryResourceImpl.java, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/Structures.java, unreleased_changes/20240515_170459_752__4272.md
=> PR for #4272 - Function completion snippets are broken in Query and expression editors

stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/ScheduledQueryAnalyticExecutor.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/TableBuilderAnalyticExecutor.java, stroom-app/src/test/java/stroom/explorer/TestExplorerTreePerformance.java, stroom-app/src/test/java/stroom/meta/impl/TestMetaSecurityFilter.java, stroom-app/src/test/java/stroom/meta/impl/TestMetaService.java, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-core-shared/src/main/java/stroom/security/shared/User.java, stroom-importexport/stroom-importexport-impl/build.gradle, stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ContentPackImport.java, stroom-importexport/stroom-importexport-impl/src/main/java/stroom/importexport/impl/ContentPackImportConfig.java, stroom-importexport/stroom-importexport-impl/src/test/java/stroom/importexport/impl/TestContentPackZipImport.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/DataProcessorTaskHandler.java, stroom-processor/stroom-processor-impl/src/main/java/stroom/processor/impl/ProcessorTaskCreatorImpl.java, stroom-security/stroom-security-api/src/main/java/stroom/security/api/SecurityContext.java, stroom-security/stroom-security-identity-db/src/main/java/stroom/security/identity/db/AccountDaoImpl.java, stroom-security/stroom-security-impl-db/src/main/java/stroom/security/impl/db/UserDaoImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/AuthenticationService.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityContextImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserCache.java, stroom-security/stroom-security-mock/src/main/java/stroom/security/mock/MockSecurityContext.java, unreleased_changes/20240516_163255_647__4262.md
=> PR for #4262 - Auto content import on boot needs to be done as a configured user

stroom-app/src/main/resources/ui/css/celltable/Menu.css, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-core-client-widget/src/main/java/stroom/widget/util/client/KeyBinding.java, stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, stroom-core-client/src/main/java/stroom/explorer/client/NavigationPlugin.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/UiConfig.java, unreleased_changes/20240522_164221_607__4287.md, unreleased_changes/20240522_164255_541__0.md, unreleased_changes/20240522_164319_275__0.md
=> PR for #4287 - Add shortcut codes for Create content to Explorer Context Menu 

stroom-security/stroom-security-impl-db/src/main/java/stroom/security/impl/db/UserDaoImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/TestAppPermissionServiceImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/TestDocumentPermissionsServiceImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/TestUserServiceImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/db/SecurityTestUtil.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/db/TestApiKeyDaoImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/db/TestAppPermissionDaoImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/db/TestDocPermissionDaoImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/db/TestUserDaoImpl.java, stroom-security/stroom-security-impl-db/src/test/java/stroom/security/impl/db/UserDaoImplTest.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserDao.java, unreleased_changes/20240528_170128_519__4299.md
=> PR for #4299 - Exception when using --createUser in the manageUsers CLI command

stroom-core/src/main/java/stroom/core/dataprocess/AbstractProcessorTaskExecutor.java, stroom-pipeline/src/main/java/stroom/pipeline/xml/converter/ds3/ComplexRegexException.java, stroom-pipeline/src/main/java/stroom/pipeline/xml/converter/ds3/DS3Parser.java, stroom-pipeline/src/main/java/stroom/pipeline/xml/converter/ds3/Regex.java, stroom-pipeline/src/main/java/stroom/pipeline/xml/converter/ds3/RegexFactory.java, unreleased_changes/20240529_180706_036__4303.md
=> PR for #4303 - StackOverflowError with data splitter

stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerTreeFilterBuilder.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/FindPresenter.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/RecentItemsPresenter.java, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerConstants.java, stroom-core-shared/src/main/java/stroom/explorer/shared/FindResult.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, unreleased_changes/20240605_091635_818__4281.md
=> PR for #4281 - Recent items is displaying am UI error when invoked (sometimes)

stroom-config/stroom-config-global-impl-db/build.gradle, stroom-config/stroom-config-global-impl-db/src/main/java/stroom/config/global/impl/db/ConfigPropertyDaoImpl.java, stroom-config/stroom-config-global-impl-db/src/test/java/stroom/config/global/impl/db/GlobalConfigTestModule.java, stroom-config/stroom-config-global-impl-db/src/test/java/stroom/config/global/impl/db/TestConfigPropertyDaoImpl.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/ConfigMapper.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/ConfigPropertyDao.java, stroom-config/stroom-config-global-impl/src/main/java/stroom/config/global/impl/GlobalConfigBootstrapService.java, stroom-util-shared/src/test/java/stroom/util/shared/TestPropertyPath.java, unreleased_changes/20240611_141505_789__4306.md
=> PR for #4306 - Properties failing to add a DB value

stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaFeedDaoImpl.java, stroom-meta/stroom-meta-impl-db/src/test/java/stroom/meta/impl/db/TestMetaFeedDaoImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/EffectiveStreamCache.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/EffectiveStreamService.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/RefDataStoreHolder.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceData.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestEffectiveStreamCache.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestRefDataStoreHolder.java, unreleased_changes/20240614_173931_498__2897.md
Relates to (but doesn't fix) #2897
=> gh-2897 Add more tests and more debug

stroom-core-client-widget/src/main/java/stroom/svg/client/SvgPresets.java, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionImpactPresenter.java, stroom-core-client/src/main/java/stroom/task/client/presenter/TaskManagerListPresenter.java, stroom-core-client/src/main/java/stroom/task/client/presenter/UserTaskManagerPresenter.java, stroom-core-client/src/main/java/stroom/task/client/view/UserTaskManagerViewImpl.java, stroom-core-shared/src/main/java/stroom/task/shared/TaskProgress.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskManagerImpl.java, unreleased_changes/20240621_100855_892__4305.md, unreleased_changes/20240621_101004_391__0.md
=> PR for #4305 - Server Tasks is querying non-enabled nodes and showing an Error Triangle

stroom-dictionary/stroom-dictionary-impl/src/main/java/stroom/dictionary/impl/DictionaryStoreImpl.java, stroom-dictionary/stroom-dictionary-impl/src/test/java/stroom/dictionary/impl/TestDictionaryStoreImpl.java, unreleased_changes/20240704_140849_987__4348.md
=> PR for #4348 - Emptied Dictionary causing ERROR in Rule

stroom-app/src/main/resources/ui/noauth/swagger/stroom.json, stroom-app/src/main/resources/ui/noauth/swagger/stroom.yaml, stroom-core-shared/src/main/java/stroom/data/shared/DataResource.java, stroom-data/stroom-data-store-api/src/main/java/stroom/data/store/api/DataService.java, stroom-data/stroom-data-store-impl-fs/src/main/java/stroom/data/store/impl/fs/FsStore.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/AttributeMapFactory.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataDownloadResourceImpl.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataResourceImpl.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataServiceImpl.java, stroom-data/stroom-data-store-impl/src/main/java/stroom/data/store/impl/DataStoreModule.java, stroom-data/stroom-data-store-mock/src/main/java/stroom/data/store/mock/MockDataService.java, stroom-data/stroom-data-store-mock/src/main/java/stroom/data/store/mock/MockStreamStoreModule.java, stroom-headless/build.gradle, stroom-headless/src/main/java/stroom/headless/CliModule.java, stroom-pipeline/build.gradle, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/MetaAttribute.java, stroom-ui/src/api/stroom.ts
Closes #4367 
Example:
```xml
<ProcessingNode>
<xsl:value-of select="stroom:meta-attribute('Processing Node')" />
</ProcessingNode>
```
=> Add `meta-attribute()` XSLT function

stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/DocRefInfoCache.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/DocPermissionResourceImpl.java, unreleased_changes/20240723_143755_577__4385.md
=> PR for #4385 - NPE When Viewing a Folder

stroom-query/stroom-query-language/src/main/java/stroom/query/language/functions/ExpressionParser.java, stroom-query/stroom-query-language/src/test/java/stroom/query/language/functions/AbstractExpressionParserTest.java, stroom-query/stroom-query-language/src/test/java/stroom/query/language/functions/TestExpressionParser.java, unreleased_changes/20240723_145300_597__4384.md
=> PR for #4384 - ERROR is thrown in the log when StroomQL contains incorrect expressions

stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/QueryServiceImpl.java, unreleased_changes/20240724_164427_410__4389.md
=> PR for #4389 - Query Table is redrawing too often

stroom-core-shared/src/main/java/stroom/pipeline/shared/XPathFilter.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/stepping/SteppingFilterSettings.java, stroom-pipeline/src/main/java/stroom/pipeline/filter/NamespaceContextImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/filter/SAXEventRecorder.java, stroom-pipeline/src/test/java/stroom/pipeline/filter/TestXPathFilter.java, unreleased_changes/20240801_143211_012__4394.md, unreleased_changes/20240801_143416_060__4395.md
=> PR for #4394 & #4395 - Stepping xpath filter bugs

stroom-app/src/test/java/stroom/data/store/impl/fs/TestFileSystemStreamStore.java, stroom-app/src/test/java/stroom/data/store/impl/fs/TestS3StreamStore.java, stroom-app/src/test/java/stroom/pipeline/refdata/TestReferenceData.java, stroom-app/src/test/java/stroom/pipeline/refdata/TestReferenceDataWithCache.java, stroom-app/src/test/resources/logback-test.xml, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/EffectiveMeta.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/EffectiveMetaSet.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/MetaService.java, stroom-meta/stroom-meta-api/src/test/java/stroom/meta/api/TestEffectiveMeta.java, stroom-meta/stroom-meta-api/src/test/java/stroom/meta/api/TestEffectiveMetaSet.java, stroom-meta/stroom-meta-impl-db/src/main/java/stroom/meta/impl/db/MetaDaoImpl.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaDao.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaServiceImpl.java, stroom-meta/stroom-meta-mock/src/main/java/stroom/meta/mock/MockMetaService.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/EffectiveStreamCache.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/EffectiveStreamInternPool.java, stroom-pipeline/src/main/java/stroom/pipeline/refdata/EffectiveStreamService.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestEffectiveStreamCache.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestEffectiveStreamInternPool.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestEffectiveStreamService.java, unreleased_changes/20240808_175424_945__2897.md
=> PR for #2897 - Ref data lookups fail intermittently

stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/ScheduledQueryAnalyticExecutor.java, stroom-app-gwt/src/main/java/stroom/app/client/App.java, stroom-app/src/main/resources/ui/css/Login.css, stroom-core-client/src/main/java/stroom/core/client/presenter/CorePresenter.java, stroom-core-client/src/main/java/stroom/security/identity/client/gin/ChangePasswordGinjector.java, stroom-core-client/src/main/java/stroom/security/identity/client/gin/ChangePasswordModule.java, stroom-core-client/src/main/java/stroom/security/identity/client/presenter/AuthenticationErrorPresenter.java, stroom-core-client/src/main/java/stroom/security/identity/client/presenter/LoginPresenter.java, stroom-core-client/src/main/java/stroom/security/identity/client/view/AuthenticationErrorViewImpl.java, stroom-core-client/src/main/java/stroom/security/identity/client/view/LoginViewImpl.java, stroom-core-client/src/main/resources/stroom/security/identity/client/view/AuthenticationErrorViewImpl.ui.xml, stroom-core-shared/src/main/java/stroom/ui/config/shared/ExtendedUiConfig.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/UiConfig.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexFieldServiceImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/authenticate/AuthenticationServiceImpl.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/authenticate/api/AuthenticationService.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/openid/OpenIdService.java, unreleased_changes/20240729_091151_154__4383.md
=> PR for #4383 - When an inactive Stroom User authenticates they get taken to a password page, this doesn't seem correct.

stroom-core-client-widget/src/main/java/stroom/widget/util/client/KeyBinding.java, unreleased_changes/20240829_140741_443__4412.md
=> PR for #4412 - Cannot type `info:/blah` in Server Tasks Quick Filter

stroom-index/stroom-index-impl-db/src/main/java/stroom/index/impl/db/IndexShardDaoImpl.java, stroom-index/stroom-index-impl/src/main/java/stroom/index/impl/IndexShardCreatorImpl.java, unreleased_changes/20240904_102313_695__4426.md
=> PR for #4426 - New INFO message when an index shard is created

stroom-core-client/src/main/java/stroom/data/store/impl/fs/client/presenter/FsVolumeGroupEditPresenter.java, stroom-core-client/src/main/java/stroom/data/store/impl/fs/client/presenter/FsVolumeStatusListPresenter.java, stroom-core-client/src/main/java/stroom/index/client/presenter/IndexVolumeGroupEditPresenter.java, stroom-core-client/src/main/java/stroom/index/client/presenter/IndexVolumeStatusListPresenter.java, unreleased_changes/20240904_132350_010__4425.md
=> PR for #4425 - Edit Volume Group - Usage Date / Total heading alignment looks off

stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SessionListServlet.java, unreleased_changes/20240904_155503_937__4418.md
=> PR for #4418 - /stroom/sessionList has no .css applied

stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/AnalyticsServiceImpl.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/RuleEmailTemplatingService.java, stroom-analytics/stroom-analytics-impl/src/test/java/stroom/analytics/impl/TestRuleEmailTemplatingService.java, stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-core-shared/src/main/java/stroom/ui/config/shared/AnalyticUiDefaultConfig.java, unreleased_changes/20240919_131039_309__4463.md
=> PR for #4463 - v7.4 Email NPE when Alerting a Streaming Analytic

stroom-core-client/src/main/java/stroom/pipeline/stepping/client/presenter/SteppingFilterPresenter.java, unreleased_changes/20240924_080534_262__4471.md
=> PR for #4471 - Can't set a filter when stepping in v.75

stroom-config/stroom-config-global-impl-db/src/main/java/stroom/config/global/impl/db/UserPreferencesDaoImpl.java, stroom-core-client-widget/src/main/java/edu/ycp/cs/dh/acegwt/client/ace/AceEditor.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/AbstractEditorPresenter.java, stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/BaseEditorView.java, stroom-core-client-widget/src/main/java/stroom/editor/client/view/AbstractEditorViewImpl.java, stroom-core-client-widget/src/main/java/stroom/editor/client/view/Editor.java, stroom-core-client/src/main/java/stroom/dashboard/client/vis/VisPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/TextPresenter.java, stroom-core-client/src/main/java/stroom/entity/client/presenter/MarkdownConverter.java, stroom-core-client/src/main/java/stroom/preferences/client/EditorPreferencesPresenter.java, stroom-core-client/src/main/java/stroom/preferences/client/UserPreferencesManager.java, stroom-core-client/src/main/java/stroom/preferences/client/UserPreferencesPresenter.java, stroom-core-client/src/main/java/stroom/query/client/presenter/QueryResultVisPresenter.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/AceEditorTheme.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/Theme.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/ThemeCssUtil.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/ThemeType.java, stroom-core-shared/src/main/java/stroom/ui/config/shared/UserPreferences.java, unreleased_changes/20240924_124617_083__4472.md
=> PR for #4472 - v7.5 User pref for some users is broken

stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/FormatDate.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestFormatDate.java, unreleased_changes/20240930_132512_706__4486.md
=> PR for #4486 - stroom:format-date() Parsing Issues when Day of Week Specified

stroom-core-client/src/main/java/stroom/core/client/ContentManager.java, stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, stroom-core-client/src/main/java/stroom/entity/client/presenter/CopyDocumentPresenter.java, stroom-core-client/src/main/java/stroom/entity/client/presenter/MoveDocumentPresenter.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/EntityTreePresenter.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerPopupPresenter.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerTreeModel.java, stroom-explorer/stroom-explorer-api/src/main/java/stroom/explorer/api/ExplorerNodeService.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerNodeServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/MockExplorerNodeService.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestFormatDate.java, unreleased_changes/20240930_160321_036__4458.md
=> PR for #4458 - Copying an Extraction Pipeline fails to copy the Extraction Tag with it

stroom-core-client-widget/src/main/java/stroom/widget/tab/client/event/RequestCloseTabEvent.java, stroom-core-client-widget/src/main/java/stroom/widget/tab/client/presenter/CurveTabLayoutPresenter.java, stroom-core-client/src/main/java/stroom/content/client/ContentPlugin.java, stroom-core-client/src/main/java/stroom/content/client/event/CloseContentTabEvent.java, stroom-core-client/src/main/java/stroom/content/client/presenter/ContentTabPanePresenter.java, stroom-core-client/src/main/java/stroom/core/client/ContentManager.java, stroom-core-client/src/main/java/stroom/core/client/event/CloseContentEvent.java, stroom-core-client/src/main/java/stroom/document/client/DocumentPlugin.java, stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, stroom-core-client/src/main/java/stroom/document/client/event/DeleteDocumentEvent.java, stroom-core-client/src/main/java/stroom/document/client/event/RenameDocumentEvent.java, stroom-core-client/src/main/java/stroom/pipeline/stepping/client/presenter/SteppingContentTabPresenter.java, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionPresenter.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestFormatDate.java, unreleased_changes/20241002_095435_568__4491.md
=> PR for #4491 - Deleting an explorer tree item closes the selected tab regardless of what the tab is

stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerPopupPresenter.java, stroom-pipeline/src/main/java/stroom/pipeline/stepping/SteppingService.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20241002_142919_719__4502.md
=> PR for #4502 - 7.5 Cannot step a stream that has not been previously processed

stroom-core-client-widget/src/main/java/stroom/data/client/event/DataSelectionEvent.java, stroom-core-client-widget/src/main/java/stroom/widget/button/client/ButtonView.java, stroom-core-client/src/main/java/stroom/data/client/presenter/AbstractMetaListPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/MetaPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/SelectionSummaryPresenter.java, stroom-core-shared/src/main/java/stroom/meta/shared/MetaResource.java, stroom-core-shared/src/main/java/stroom/meta/shared/SelectionSummaryRequest.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/MetaService.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaResourceImpl.java, stroom-meta/stroom-meta-impl/src/main/java/stroom/meta/impl/MetaServiceImpl.java, stroom-meta/stroom-meta-mock/src/main/java/stroom/meta/mock/MockMetaService.java, stroom-util-shared/src/main/java/stroom/util/shared/ResultPage.java, unreleased_changes/20241003_093119_404__4503.md
=> PR for #4503 - Delete Functionality Appears Available for Users without Delete Permissions

stroom-app/src/main/java/stroom/app/db/migration/V07_05_00_005__Orphaned_Doc_Perms.java, unreleased_changes/20241007_153507_922__4513.md
=> PR for #4513 - Doc perms migration fails in InnoDB Cluster deployments

stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/AuthProxyResourceImpl.java, unreleased_changes/20241007_155347_025__4514.md
=> PR for #4514 - Auth proxy endpoint causes a HTTP redirect

stroom-query/stroom-query-common/src/main/java/stroom/query/common/v2/ResultStoreManager.java, stroom-statistics/stroom-statistics-impl-sql/src/main/java/stroom/statistics/impl/sql/search/StatisticsSearchServiceImpl.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20241008_112056_114__4487.md
=> PR for #4487 - Stats Query with no columns in table gives Alert

stroom-core-client/src/main/java/stroom/explorer/client/presenter/AbstractExplorerTree.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/ExplorerTreeModel.java, unreleased_changes/20241008_124900_066__4498.md
=> PR for #4498 - Explorer: Expand / Collapse does not respect the Quick Filter

stroom-core-client/src/main/java/stroom/data/client/presenter/DataUploadPresenter.java, stroom-core-client/src/main/java/stroom/data/client/view/DataUploadViewImpl.java, unreleased_changes/20241008_132029_976__4518.md
=> PR for #4518 - Stream Manual Upload, please default the Type to be the Default Type specified on the Feed

stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/FunctionSignatureUtil.java, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/Functions.java, stroom-query/stroom-query-impl/src/test/java/stroom/query/impl/TestFunctionSignatureUtil.java, stroom-query/stroom-query-impl/src/test/java/stroom/query/impl/TestFunctions.java, unreleased_changes/20241008_170516_405__4460.md
=> PR for #4460 - distinct with sort isn't being shown correctly in the query helper

stroom-core-client/src/main/java/stroom/dictionary/client/presenter/DictionaryPresenter.java, stroom-core-client/src/main/java/stroom/dictionary/client/presenter/WordListPresenter.java, stroom-core-shared/src/main/java/stroom/dictionary/shared/WordList.java, stroom-core-shared/src/test/java/stroom/dictionary/shared/TestWordList.java, stroom-dictionary/stroom-dictionary-impl/src/main/java/stroom/dictionary/impl/DictionaryStoreImpl.java, stroom-docref/src/main/java/stroom/docref/DocRef.java, stroom-util/src/main/java/stroom/util/string/StringUtil.java, stroom-util/src/test/java/stroom/util/string/TestStringUtil.java, unreleased_changes/20241009_152941_767__4526.md
=> PR for #4526 - stroom:dictionary() is dropping { and } when on a separate line

stroom-core-shared/src/main/java/stroom/job/shared/JobNode.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobBootstrap.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobNodeService.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/JobNodeTrackerCacheImpl.java, stroom-job/stroom-job-impl/src/main/java/stroom/job/impl/ScheduledTaskExecutor.java, stroom-util-shared/src/main/java/stroom/util/shared/scheduler/ScheduleType.java, stroom-util/src/main/java/stroom/util/scheduler/SimpleScheduleExec.java, unreleased_changes/20241010_123207_271__4532.md
=> PR for #4532 - `Run Now` doesn't work if the job or jobNode is disabled

stroom-index/stroom-index-lucene980/src/main/java/stroom/contentindex/ContentIndexModule.java, stroom-index/stroom-index-lucene980/src/main/java/stroom/contentindex/LuceneContentIndex.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskContextImpl.java, stroom-task/stroom-task-impl/src/main/java/stroom/task/impl/TaskThreadInfoUtil.java, unreleased_changes/20241010_110014_476__4528.md
=> PR for #4528 - Content Re-Index job isn't interruptible on shutdown

stroom-app/src/main/resources/ui/css/components.css, stroom-core-client/src/main/java/stroom/explorer/client/presenter/FindInContentPresenter.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/FindInContentResultCell.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/FindResultCell.java, stroom-core-client/src/main/java/stroom/explorer/client/presenter/RecentItemsPresenter.java, stroom-docref/src/main/java/stroom/docref/DocContentMatch.java, stroom-index/stroom-index-lucene980/src/main/java/stroom/contentindex/ContentIndexImpl.java, stroom-index/stroom-index-lucene980/src/main/java/stroom/contentindex/LuceneContentHighlighter.java, stroom-index/stroom-index-lucene980/src/main/java/stroom/contentindex/LuceneContentIndex.java, unreleased_changes/20241015_092609_888__4527.md
=> PR for #4527 - Content Search, can't seem to search for `stroom:`

stroom-core-client/src/main/java/stroom/data/client/presenter/DocRefCell.java, stroom-core-client/src/main/java/stroom/data/client/presenter/ProcessorTaskListPresenter.java, stroom-core-client/src/main/java/stroom/data/client/presenter/ProcessorTaskSummaryPresenter.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PipelineReferenceListPresenter.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PropertyListPresenter.java, stroom-core-client/src/main/java/stroom/processor/client/presenter/ProcessorListPresenter.java, stroom-core-client/src/main/java/stroom/util/client/DataGridUtil.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/PipelineDataMerger.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/OpenItemsImpl.java, stroom-util/src/main/java/stroom/util/NullSafe.java, stroom-util/src/test/java/stroom/util/TestNullSafe.java, unreleased_changes/20241028_151104_716__0.md, unreleased_changes/20241028_153230_559__4560.md, unreleased_changes/20241028_160934_129__4570.md
Addresses some of #4560
Fixes #4570
=> PR for #4560 - UI is sorting Ref Loader entries (by name?)

stroom-core-client/src/main/java/stroom/document/client/DocumentPluginEventManager.java, stroom-core-shared/src/main/java/stroom/explorer/shared/ExplorerConstants.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerNodeServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/FolderExplorerActionHandler.java, unreleased_changes/20241106_152301_552__0.md, unreleased_changes/20241106_152811_215__4588.md, unreleased_changes/20241106_153011_961__0.md, unreleased_changes/20241106_153138_954__0.md
=> PR for #4588 - Explorer API allows document move with only VIEW permission

stroom-core-client/src/main/java/stroom/explorer/client/presenter/DocumentPermissionsListPresenter.java, stroom-core-client/src/main/java/stroom/importexport/client/presenter/DependenciesPresenter.java, stroom-core-client/src/main/java/stroom/security/client/presenter/UserPermissionReportPresenter.java, stroom-core-shared/src/main/java/stroom/entity/shared/ExpressionCriteria.java, stroom-core-shared/src/main/java/stroom/explorer/shared/AdvancedDocumentFindRequest.java, stroom-core-shared/src/main/java/stroom/explorer/shared/AdvancedDocumentFindWithPermissionsRequest.java, stroom-core-shared/src/main/java/stroom/explorer/shared/FindResult.java, stroom-core-shared/src/main/java/stroom/explorer/shared/FindResultWithPermissions.java, stroom-util-shared/src/main/java/stroom/util/shared/BaseCriteria.java, stroom-util-shared/src/main/java/stroom/util/shared/GwtNullSafe.java, stroom-util-shared/src/main/java/stroom/util/shared/PageRequest.java, stroom-util-shared/src/test/java/stroom/util/shared/TestGwtNullSafe.java, unreleased_changes/20241106_190848_044__4586.md
=> PR for #4586 - Error when filtering User Perms Report

stroom-app/src/main/resources/ui/css/stroom-dashboard.css, unreleased_changes/20241119_112149_086__4606.md
=> PR for #4606 - Unable to scroll a Dashboard text pane that is set to show as HTML

stroom-core-client/src/main/java/stroom/dashboard/client/main/DashboardPresenter.java, stroom-core-client/src/main/java/stroom/dashboard/client/table/cf/RuleListPresenter.java, stroom-core-client/src/main/java/stroom/dashboard/client/table/cf/RulesPresenter.java, stroom-core-shared/src/main/java/stroom/dashboard/shared/TableComponentSettings.java, stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/ConditionalFormattingRule.java, stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/ExpressionOperator.java, stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/Filter.java, stroom-query/stroom-query-api/src/test/resources/searchRequestPortrait-current.txt, stroom-query/stroom-query-api/src/test/resources/searchRequestPortrait-new.txt, stroom-util-shared/src/main/java/stroom/util/shared/GwtNullSafe.java, stroom-util-shared/src/test/java/stroom/util/shared/TestGwtNullSafe.java, unreleased_changes/20241122_113114_669__4611.md
=> PR for #4611 - Dashboard, duplicate a table that has Conditional Formatting, both tables use the same Rules

stroom-query/stroom-query-api/src/main/java/stroom/query/api/v2/ResultRequest.java, stroom-query/stroom-query-impl/src/main/java/stroom/query/impl/QueryServiceImpl.java, unreleased_changes/20241122_123904_569__4612.md
=> PR for #4612 - Stroom QL with show will only display values from the first page of results

stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/DetectionWriter.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/DetectionsWriter.java, stroom-analytics/stroom-analytics-impl/src/main/java/stroom/analytics/impl/ScheduledQueryAnalyticExecutor.java, stroom-core-shared/src/main/java/stroom/analytics/shared/ExecutionTracker.java, stroom-docstore/stroom-docstore-impl/src/main/java/stroom/docstore/impl/StoreImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/factory/ProcessorFactoryImpl.java, unreleased_changes/20241122_161136_201__4617.md
=> PR for #4617 - Analytic Rule perm issue when Executing

stroom-security/stroom-security-impl-db/src/main/resources/stroom/security/impl/db/migration/V07_06_00_915__drop_foreign_keys_to_stroom_user.sql, unreleased_changes/20241220_093941_640__4671.md
=> PR for #4671 - doc_permission table (now unused) still has a constraint to stroom_user, causes deletions to fail

setProxyLogLevels.sh, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/Aggregator.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/SimpleReceiver.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/StoringReceiverFactory.java, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/StroomStreamProcessor.java, unreleased_changes/20250311_162313_888__4808.md
=> PR for #4808 - proxy 7.8 sending gzipped data inside a proxy zip

stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionImpactPresenter.java, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionImpactRow.java, stroom-core-client/src/main/java/stroom/receive/rules/client/presenter/DataRetentionPolicyListPresenter.java, unreleased_changes/20250326_122512_582__4831.md
=> PR for #4831 - Data Retention Impact Summary is not showing any results

stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/OpenIdManager.java, unreleased_changes/20250401_122052_052__4842.md
=> PR for #4842 - OIDC code flow is broken when using Keycloack IDP

stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/DirQueue.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/HttpSender.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/PreAggregator.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ProxyRequestHandler.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/RemoteFeedStatusService.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ZipReceiver.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ZipWriter.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/TestProxyConfigModule.java, stroom-proxy/stroom-proxy-remote-api/src/main/java/stroom/proxy/feed/remote/GetFeedStatusRequest.java, stroom-proxy/stroom-proxy-repo/src/main/java/stroom/proxy/repo/FrequencyExecutor.java, stroom-proxy/stroom-proxy-repo/src/main/java/stroom/proxy/repo/ParallelExecutor.java, stroom-util/src/main/java/stroom/util/logging/LogUtil.java, stroom-util/src/main/java/stroom/util/zip/ZipUtil.java, unreleased_changes/20250415_163812_915__4863.md, unreleased_changes/20250415_171225_150__4879.md
=> Various proxy issues

stroom-resource/stroom-resource-impl/build.gradle, stroom-resource/stroom-resource-impl/src/main/java/stroom/resource/impl/SessionResourceStoreImpl.java, unreleased_changes/20250420_045158_099__4889.md
=> Include .zip file extension when accessing stream downloads

stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/DataFeedKeyServiceImpl.java, unreleased_changes/20250429_121758_229__4927.md
=> PR for #4927 - Stroom 7.9 rejecting /datafeed token auth

stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/AbstractUserIdentityFactory.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/StandardJwtContextFactory.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/UserIdentitySessionUtil.java, stroom-security/stroom-security-identity/src/main/java/stroom/security/identity/authenticate/AuthenticationServiceImpl.java, stroom-security/stroom-security-identity/src/test/java/stroom/security/identity/token/TestJwkFactoryImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/OpenIdManager.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityFilter.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/StroomUserIdentityFactory.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/apikey/ApiKeyService.java, stroom-util/src/main/java/stroom/util/servlet/UserAgentSessionUtil.java, unreleased_changes/20250429_143223_698__0.md, unreleased_changes/20250430_094707_582__4892.md
=> PR for #4892 - external IdP Stroom User is not checking enabled state on login

stroom-core-client-widget/src/main/java/stroom/editor/client/presenter/Option.java, stroom-core-client-widget/src/main/java/stroom/editor/client/view/EditorMenuPresenter.java, unreleased_changes/20250430_131400_229__4893.md
=> PR for #4893 - Right click in editor not displaying correctly

stroom-core-client/src/main/java/stroom/explorer/client/presenter/DocSelectionBoxPresenter.java, stroom-core-client/src/main/java/stroom/view/client/presenter/ViewSettingsPresenter.java, stroom-query/stroom-query-common/build.gradle, stroom-query/stroom-query-common/src/main/java/stroom/query/language/SearchRequestFactory.java, stroom-query/stroom-query-common/src/test/java/stroom/query/language/MockDocResolver.java, stroom-query/stroom-query-common/src/test/java/stroom/query/language/TestSearchRequestFactory.java, stroom-query/stroom-query-common/src/test/java/stroom/query/language/TestSearchRequestFactory2.java, stroom-search/stroom-search-extraction/src/main/java/stroom/search/extraction/ExtractionDecorator.java, stroom-security/stroom-security-mock/src/main/java/stroom/security/mock/MockSecurityContext.java, unreleased_changes/20250430_162813_453__4916.md, unreleased_changes/20250430_162919_583__0.md
=> PR for #4916 - App perms, User requires View on a View to be able to download Query results

stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CommonXsltFunctionModule.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/CurrentUnixTime.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/FromUnixTime.java, stroom-pipeline/src/main/java/stroom/pipeline/xsltfunctions/ToUnixTime.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestCurrentUnixTime.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestFromUnixTime.java, stroom-pipeline/src/test/java/stroom/pipeline/xsltfunctions/TestToUnixTime.java
=> Add unix-time XSLT functions

stroom-app/src/main/resources/ui/css/components.css, stroom-app/src/main/resources/ui/css/stroom.css, stroom-app/src/main/resources/ui/css/theme-dark.css, stroom-app/src/main/resources/ui/css/theme-root.css, stroom-app/src/main/resources/ui/css/tickbox.css, stroom-core-client-widget/src/main/java/stroom/cell/tickbox/client/TickBoxCell.java, stroom-core-client-widget/src/main/java/stroom/svg/client/SvgPresets.java, stroom-core-client-widget/src/main/java/stroom/widget/form/client/FormGroup.java, stroom-core-client-widget/src/main/java/stroom/widget/form/client/FormLabel.java, stroom-core-client/src/main/java/stroom/pipeline/structure/client/presenter/PipelineStructurePresenter.java, stroom-core-client/src/main/java/stroom/receive/content/client/presenter/ContentTemplateEditPresenter.java, stroom-core-client/src/main/java/stroom/receive/content/client/presenter/ContentTemplateListPresenter.java, stroom-core-client/src/main/java/stroom/receive/content/client/presenter/ContentTemplateTabPresenter.java, stroom-core-client/src/main/java/stroom/receive/content/client/view/ContentTemplateEditViewImpl.java, stroom-core-client/src/main/java/stroom/util/client/DataGridUtil.java, stroom-core-client/src/main/resources/stroom/receive/content/client/view/ContentTemplateEditViewImpl.ui.xml, stroom-core-shared/src/main/java/stroom/pipeline/shared/PipelineDoc.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/data/PipelineElements.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/data/PipelineLinks.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/data/PipelineProperties.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/data/PipelineProperty.java, stroom-core-shared/src/main/java/stroom/pipeline/shared/data/PipelineReferences.java, stroom-core-shared/src/main/java/stroom/receive/content/shared/ContentTemplate.java, stroom-core-shared/src/test/java/stroom/receive/content/TestContentTemplates.java, stroom-core/src/main/java/stroom/core/receive/ContentAutoCreationServiceImpl.java, stroom-docstore/stroom-docstore-api/src/main/java/stroom/docstore/api/DependencyRemapper.java, stroom-explorer/stroom-explorer-impl/src/main/java/stroom/explorer/impl/ExplorerServiceImpl.java, stroom-pipeline/src/main/java/stroom/pipeline/PipelineServiceImpl.java, unreleased_changes/20250620_140619_797__4969.md
=> PR for #4969 - Content Templates to create copies of linked items

stroom-core/src/main/java/stroom/core/receive/AutoContentCreationConfig.java, stroom-core/src/main/java/stroom/core/receive/ContentAutoCreationServiceImpl.java, stroom-core/src/main/java/stroom/core/receive/FeedStatusServiceImpl.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/StandardJwtContextFactory.java, unreleased_changes/20250729_124050_491__5046.md
=> PR for #5046 - autoContentCreation creates feeds even when they lack the correct headers

stroom-config/stroom-config-app/src/test/resources/stroom/config/app/expected.yaml, stroom-core/src/main/java/stroom/core/receive/ContentAutoCreationServiceImpl.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/security/ProxyUserIdentityFactory.java, stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml, stroom-receive/stroom-receive-common/src/main/java/stroom/receive/common/FeedNameCheckAttributeMapFilter.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/AbstractUserIdentityFactory.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/StandardJwtContextFactory.java, stroom-security/stroom-security-common-impl/src/test/java/stroom/security/common/impl/TestStandardJwtContextFactory.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/StroomUserIdentityFactory.java, stroom-security/stroom-security-openid-api/src/main/java/stroom/security/openid/api/AbstractOpenIdConfig.java, stroom-util/src/main/java/stroom/util/io/SimplePathCreator.java, stroom-util/src/main/java/stroom/util/string/TemplateUtil.java, stroom-util/src/test/java/stroom/util/string/TestTemplateUtil.java, unreleased_changes/20250820_110802_226__5066.md
=> PR for #5066 - Use named params in the openid.publicKeyUriPattern prop

stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/AbstractUserIdentityFactory.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/StandardJwtContextFactory.java, stroom-util/src/main/java/stroom/util/string/TemplateUtil.java, stroom-util/src/test/java/stroom/util/string/TestTemplateUtil.java, unreleased_changes/20250827_094137_948__5077.md
=> PR for #5077 - All users are getting the fullName of the first user to log in

stroom-pipeline/src/main/java/stroom/pipeline/refdata/ReferenceDataFilter.java, stroom-pipeline/src/test/java/stroom/pipeline/refdata/TestReferenceDataFilter.java, stroom-pipeline/src/test/resources/TestReferenceDataFilter/input_FastInfosetValue_1.xml, stroom-pipeline/src/test/resources/TestReferenceDataFilter/input_FastInfosetValue_2.xml, stroom-pipeline/src/test/resources/TestReferenceDataFilter/input_FastInfosetValue_3.xml, stroom-pipeline/src/test/resources/TestReferenceDataFilter/input_FastInfosetValue_4.xml, stroom-pipeline/src/test/resources/TestReferenceDataFilter/input_FastInfosetValue_6.xml, stroom-pipeline/src/test/resources/TestReferenceDataFilter/input_FastInfosetValue_7.xml, stroom-pipeline/src/test/resources/TestReferenceDataFilter/input_FastInfosetValue_8.xml, stroom-pipeline/src/test/resources/logback-test.xml, unreleased_changes/20250909_102638_429__5106.md
=> PR for #5106 - Ref loads failing with un-namespaced XML values

stroom-dropwizard-common/src/main/java/stroom/dropwizard/common/AuthenticationBypassCheckerImpl.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/HasJwtClaims.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/JwtContextFactory.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/UpdatableToken.java, stroom-security/stroom-security-common-impl/src/main/java/stroom/security/common/impl/UserIdentitySessionUtil.java, stroom-security/stroom-security-common-impl/src/test/java/stroom/security/common/impl/TestRefreshManager.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SecurityFilter.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SessionListListener.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SessionListServlet.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/SessionResourceImpl.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/StroomUserIdentityFactory.java, stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/UserIdentityImpl.java, stroom-util-shared/src/main/java/stroom/util/shared/ResourcePaths.java, stroom-util/src/main/java/stroom/util/authentication/HasExpiry.java, stroom-util/src/main/java/stroom/util/authentication/PerishableItem.java, stroom-util/src/main/java/stroom/util/authentication/Refreshable.java, stroom-util/src/main/java/stroom/util/authentication/RefreshableItem.java, stroom-util/src/main/java/stroom/util/servlet/SessionUtil.java, unreleased_changes/20250919_133650_510__5132.md
=> PR for #5132 - /stroom/sessionList is empty on 7.10.2

stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/CIStringHashMap.java, stroom-meta/stroom-meta-api/src/main/java/stroom/meta/api/StandardHeaderArguments.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/ForwardHttpPostConfig.java, stroom-proxy/stroom-proxy-app/src/main/java/stroom/proxy/app/handler/HttpSender.java, stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/handler/TestHttpSender.java, stroom-proxy/stroom-proxy-app/src/test/resources/stroom/dist/proxy-expected.yaml, stroom-util-shared/src/main/java/stroom/util/shared/string/CIKeys.java, unreleased_changes/20250922_150101_514__5137.md
=> PR for #5137 - Proxy is forwarding with `X-Forwarded-Host` header which is breaking SNI

stroom-proxy/stroom-proxy-app/src/test/java/stroom/proxy/app/handler/TestHttpSender.java, stroom-util-shared/src/main/java/stroom/util/shared/string/CIKey.java, stroom-util-shared/src/main/java/stroom/util/shared/string/CIKeys.java, stroom-util-shared/src/test/java/stroom/util/shared/string/TestCIKey.java, unreleased_changes/20250926_112438_694__5147.md
=> PR for #5147 - Proxy not able to forward then stream uses 'feed' or 'FEED'
